### ISSUE TITLE
[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

### ISSUE THREAD

**Issue by alexander-lysenko-88** [microsoft/app-store-vsts-extension#111]
Hi 
I have some problems with **Apple App Store Release** task. 
Preconditions:
1. I use Microsoft **Hosted MacOS** agent pool
2. I try to publish my .ipa file to **production** track
3. I use **Service Connection** authentication method for connection with iTunesConnect
4. I use a separate AppleId account for my CI\CD pipelines and **2 factor authentication is turned off** for the account (as it was recommected in the instruction to the task) 
5. It's not the first publish of the App to the AppStore 

Actual result:

1. a new version of the App was created in the iTunesConnect
2. however the .ipa file was not uploaded
3. the task was in progress for about 30 minutes without any updates in the logs, thus I canceled the job in the release pipeline. This was done at timestamp _2019-02-27T17:30:16.9738120Z_ 

Logs from the task:
```
2019-02-27T17:01:08.0942530Z [17:01:08]: Making sure the la*** version on App Store Connect matches '7.0.0' from the ipa file...
2019-02-27T17:01:09.6428300Z [17:01:09]: '7.0.0' is the la*** version on App Store Connect
2019-02-27T17:01:10.2312590Z [17:01:10]: Uploading binary to App Store Connect
2019-02-27T17:01:10.8218830Z [17:01:10]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2019-02-27T17:01:10.8219900Z [17:01:10]: Going to upload updated app to App Store Connect
2019-02-27T17:01:10.8221040Z [17:01:10]: This might take a few minutes. Please don't interrupt the script.
2019-02-27T17:04:36.6188270Z [17:04:36]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
2019-02-27T17:04:36.6190800Z -------------------------------------------------------------------------------------
2019-02-27T17:04:36.6296680Z Please provide your Apple Developer Program account credentials
2019-02-27T17:04:36.6297500Z The login information you enter will be stored in your macOS Keychain
2019-02-27T17:04:36.6298020Z You can also pass the password using the `FASTLANE_PASSWORD` environment variable
2019-02-27T17:04:36.6298510Z See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
2019-02-27T17:04:36.6300170Z -------------------------------------------------------------------------------------
2019-02-27T17:30:16.9738120Z ##[debug]Re-evaluate condition on job cancellation for step: 'Publish to the App Store Production track'.
2019-02-27T17:30:16.9738360Z ##[debug]Skip Re-evaluate condition on agent shutdown.
2019-02-27T17:30:17.0056670Z ##[error]The operation was canceled.
2019-02-27T17:30:17.0061160Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2019-02-27T17:30:17.0063980Z ##[section]Finishing: Publish to the App Store Production track

```
Does anybody have an idea what I'm doing wrong? I'd appreciate for any help.

**Comment by madhurig** [comment]
There seems to be an issue with the password as per the logs
[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

Apple is mandating 2FA now (as of yesterday), you might be running into that. The extension supports 2FA, we will update the docs to not recommend turning off 2FA now. It requires a few extra steps in setup, please review the docs to set that up and also verify your password. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
To setup two factor auth, please checkout the docs: https://github.com/Microsoft/app-store-vsts-extension#two-factor-authentication.

I am closing this issue since there is no update in a month. If the issue persists, please let us know.

**Comment by alexander-lysenko-88** [comment]
First of all I want to mention that both my password and username were correct, I checked that several times. 
Next, I do not want to use 2 factor authentication for service account, it seems over-complicated for my needes. Moreover it seems that the problem was not on Apple side, it is in the **Apple App Store Release** task. When I switched **Authentication Method** from _Service Connection_ to _Username and Password_ the exception disappeared. 

Thus I assume that the task doesn't supports **Authentication Method** = _Service Connection_ in case when 2-Factor authentication is disabled for the Apple Id account you are using in the task. 

I think that the problem is in the logic, which determines whether 2-factor authentication is ON or OFF for service connection. The logic wrongly decides that 2-factor authentication is ON when it's OFF. And I think that this should be fixed.

**Comment by inforithmics** [comment]
I had the same problem I activated user password validation and fastlane always tried two factor authenticfication.

The reason was that FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD was defined in the Task Variables.

and set in the build envirment even If I had user password authentication specified.

So maybe for better reliablity of the Task 

In the user password authentification case the 

FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
FASTLANE_SESSION

Environment Variables could be specifically deleted.

**Comment by ekaterina-tatanova** [comment]
@alexander-lysenko-88  Are you still having this issue?

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by lekeCoder** [comment]
For me, I had `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` and `FASTLANE_PASSWORD` in my environment variables. So I remove `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` and it worked. Thanks @inforithmics for your input.
