### ISSUE TITLE
Building the Task fails with missing files

### ISSUE THREAD

**Issue by DaVaMa1** [microsoft/app-store-vsts-extension#161]
Hi,

I'm following the guide to build the tasks on my local machine but I get the following error when running the Gulp command:

> tsc --outDir F:\Visual Studio Code Projects\app-store-vsts-extension\_build\Tasks\AppStorePromote --rootDir F:\Visual Studio Code Projects\app-store-vsts-extension\Tasks\app-store-promote
,error TS6053: File 'Code.ts' not found.
error TS6053: File 'Projects/app-store-vsts-extension/Tasks/app-store-promote.ts' not found.     
error TS6053: File 'Projects/app-store-vsts-extension/_build/Tasks/AppStorePromote.ts' not found.
error TS6053: File 'Studio.ts' not found.
,
,,
[19:55:03] '<anonymous>' errored after 4.34 s
[19:55:03] Error: Missing error message
    at new PluginError (F:\Visual Studio Code Projects\app-store-vsts-extension\node_modules\gulp-util\lib\PluginError.js:73:28)
    at make (F:\Visual Studio Code Projects\app-store-vsts-extension\gulpfile.js:21:12)
    at F:\Visual Studio Code Projects\app-store-vsts-extension\gulpfile.js:33:5
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (F:\Visual Studio Code Projects\app-store-vsts-extension\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[19:55:03] 'build' errored after 4.36 s
[19:55:03] 'default' errored after 4.38 s
PS F:\Visual Studio Code Projects\app-store-vsts-extension> 

Am I missing an extension or something?

**Comment by DaVaMa1** [comment]
Well do I feel stupid......

Don't have spaces in your path........
