### ISSUE TITLE
AppStorePromote asks for 2FA

### ISSUE THREAD

**Issue by trajano** [microsoft/app-store-vsts-extension#190]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AppStorePromote@1

## Environment
- Server - Azure Pipelines

- Agent - Hosted macOS-latest
    
## Issue Description

Unable to execute an AppStorePromote.  It asks for 2FA.  Note I did the same work around as #153 

I tried the following

```
          - task: AppStorePromote@1
            inputs:
              authType: 'UserAndPass'
              username: 'YYY@FOO.com'
              password: 'XXX'
              isTwoFactorAuth: true
              appSpecificPassword: 'xxxx-xxxx-xxxx-xxxx'
              fastlaneSession: 'anyNotEmptyString'
              appIdentifier: com.example.app
              chooseBuild: Latest
              shouldAutoRelease: false
              # teamId: XXXXXX
              fastlaneArguments: '-p 99999'
```

And other variations

```
          - task: AppStorePromote@1
            inputs:
              serviceEndpoint: Apple App Store
              # isTwoFactorAuth: true
              # appSpecificPassword: 'xxxx-xxxx-xxxx-xxxx'
              # fastlaneSession: 'anyNotEmptyString'
              appIdentifier: com.example.app
              chooseBuild: Latest
              shouldAutoRelease: false
              # teamId: XXXXXX
              fastlaneArguments: '-p 99999'
````

### Task logs

```
2020-11-05T05:18:37.8910460Z ##[debug]Evaluating condition for step: 'AppStorePromote'
2020-11-05T05:18:37.8913350Z ##[debug]Evaluating: SucceededNode()
2020-11-05T05:18:37.8914370Z ##[debug]Evaluating SucceededNode:
2020-11-05T05:18:37.8916350Z ##[debug]=> True
2020-11-05T05:18:37.8917290Z ##[debug]Result: True
2020-11-05T05:18:37.8918290Z ##[section]Starting: AppStorePromote
2020-11-05T05:18:37.8946500Z ==============================================================================
2020-11-05T05:18:37.8946900Z Task         : Apple App Store Promote
2020-11-05T05:18:37.8947250Z Description  : Release a build from iTunes Connect to the Apple App Store
2020-11-05T05:18:37.8947570Z Version      : 1.177.2
2020-11-05T05:18:37.8947810Z Author       : Microsoft Corporation
2020-11-05T05:18:37.8948230Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2020-11-05T05:18:37.8949350Z ==============================================================================
2020-11-05T05:18:38.0942020Z ##[debug]Using node path: /Users/runner/runners/2.175.2/externals/node/bin/node
2020-11-05T05:18:38.7132230Z ##[debug]agent.TempDirectory=/Users/runner/work/_temp
2020-11-05T05:18:38.7155920Z ##[debug]loading inputs and endpoints
2020-11-05T05:18:38.7162700Z ##[debug]loading INPUT_AUTHTYPE
2020-11-05T05:18:38.7177540Z ##[debug]loading INPUT_USERNAME
2020-11-05T05:18:38.7181240Z ##[debug]loading INPUT_PASSWORD
2020-11-05T05:18:38.7182890Z ##[debug]loading INPUT_ISTWOFACTORAUTH
2020-11-05T05:18:38.7184680Z ##[debug]loading INPUT_APPSPECIFICPASSWORD
2020-11-05T05:18:38.7185810Z ##[debug]loading INPUT_FASTLANESESSION
2020-11-05T05:18:38.7186820Z ##[debug]loading INPUT_APPIDENTIFIER
2020-11-05T05:18:38.7197000Z ##[debug]loading INPUT_CHOOSEBUILD
2020-11-05T05:18:38.7198220Z ##[debug]loading INPUT_SHOULDAUTORELEASE
2020-11-05T05:18:38.7199590Z ##[debug]loading INPUT_INSTALLFASTLANE
2020-11-05T05:18:38.7201120Z ##[debug]loading INPUT_FASTLANETOOLSVERSION
2020-11-05T05:18:38.7202230Z ##[debug]loading INPUT_FASTLANEARGUMENTS
2020-11-05T05:18:38.7203880Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-11-05T05:18:38.7205110Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-11-05T05:18:38.7206200Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-11-05T05:18:38.7211740Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2020-11-05T05:18:38.7212240Z ##[debug]loaded 16
2020-11-05T05:18:38.7232120Z ##[debug]Agent.ProxyUrl=undefined
2020-11-05T05:18:38.7233190Z ##[debug]Agent.CAInfo=undefined
2020-11-05T05:18:38.7233620Z ##[debug]Agent.ClientCert=undefined
2020-11-05T05:18:38.7233990Z ##[debug]Agent.SkipCertValidation=undefined
2020-11-05T05:18:38.7250730Z ##[debug]check path : /Users/runner/work/_tasks/AppStorePromote_cbbf7f14-c386-4c1f-80a3-fe500e2bd976/1.177.2/task.json
2020-11-05T05:18:38.7251900Z ##[debug]adding resource file: /Users/runner/work/_tasks/AppStorePromote_cbbf7f14-c386-4c1f-80a3-fe500e2bd976/1.177.2/task.json
2020-11-05T05:18:38.7252790Z ##[debug]system.culture=en-US
2020-11-05T05:18:38.7265210Z ##[debug]Reading all inputs...
2020-11-05T05:18:38.7274220Z ##[debug]authType=UserAndPass
2020-11-05T05:18:38.7281250Z ##[debug]username=XXXXXXXXXXXXXXXXXX
2020-11-05T05:18:38.7282740Z ##[debug]password=XXXXXXXXXXXXXXXXXXXX
2020-11-05T05:18:38.7285330Z ##[debug]isTwoFactorAuth=true
2020-11-05T05:18:38.7287110Z ##[debug]appSpecificPassword=XXXXXXXXXXXXXXXXXXXXXXXXXX
2020-11-05T05:18:38.7288060Z ##[debug]fastlaneSession=anyNotEmptyString
2020-11-05T05:18:38.7289670Z ##[debug]appIdentifier=com.XXXXXXXXXXXXXXXXXXXXXX
2020-11-05T05:18:38.7290860Z ##[debug]chooseBuild=Latest
2020-11-05T05:18:38.7291340Z ##[debug]buildNumber=undefined
2020-11-05T05:18:38.7292850Z ##[debug]shouldAutoRelease=false
2020-11-05T05:18:38.7293270Z ##[debug]teamId=undefined
2020-11-05T05:18:38.7293580Z ##[debug]teamName=undefined
2020-11-05T05:18:38.7294320Z ##[debug]installFastlane=true
2020-11-05T05:18:38.7296010Z ##[debug]fastlaneToolsVersion=LatestVersion
2020-11-05T05:18:38.7297660Z ##[debug]fastlaneArguments=-p XXXXXXXXXXXXXXXXXXXXXXX
2020-11-05T05:18:38.7299130Z ##[debug]Read all inputs.
2020-11-05T05:18:38.7299520Z ##[debug]GEM_CACHE=undefined
2020-11-05T05:18:38.7300160Z ##[debug]gemCache=/Users/runner/.gem-cache
2020-11-05T05:18:38.7300850Z ##[debug]Using two-factor authentication
2020-11-05T05:18:38.7301220Z ##[debug]Checking for ruby install...
2020-11-05T05:18:38.7302030Z ##[debug]which 'ruby'
2020-11-05T05:18:38.7310110Z ##[debug]found: '/usr/local/opt/ruby/bin/ruby'
2020-11-05T05:18:38.7310590Z ##[debug]Installing fastlane...
2020-11-05T05:18:38.7311160Z ##[debug]which 'gem'
2020-11-05T05:18:38.7312720Z ##[debug]found: '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:18:38.7315020Z ##[debug]which '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:18:38.7315840Z ##[debug]found: '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:18:38.7319430Z ##[debug]/usr/local/opt/ruby/bin/gem arg: ["install","fastlane"]
2020-11-05T05:18:38.7325480Z ##[debug]exec tool: /usr/local/opt/ruby/bin/gem
2020-11-05T05:18:38.7326110Z ##[debug]arguments:
2020-11-05T05:18:38.7326680Z ##[debug]   install
2020-11-05T05:18:38.7327000Z ##[debug]   fastlane
2020-11-05T05:18:38.7334880Z [command]/usr/local/opt/ruby/bin/gem install fastlane
2020-11-05T05:19:05.8098610Z Successfully installed fastlane-2.166.0
2020-11-05T05:19:05.8099490Z Parsing documentation for fastlane-2.166.0
2020-11-05T05:19:05.8100180Z Installing ri documentation for fastlane-2.166.0
2020-11-05T05:19:05.8100600Z Done installing documentation for fastlane after 21 seconds
2020-11-05T05:19:05.8100880Z 1 gem installed
2020-11-05T05:19:05.8342620Z 
2020-11-05T05:19:05.8351350Z ##[debug]Exit code 0 received from tool '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:05.8360490Z ##[debug]STDIO streams have closed for tool '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:05.8378920Z ##[debug]Updating fastlane...
2020-11-05T05:19:05.8379840Z ##[debug]which 'gem'
2020-11-05T05:19:05.8382670Z ##[debug]found: '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:05.8383560Z ##[debug]which '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:05.8384500Z ##[debug]found: '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:05.8385450Z ##[debug]/usr/local/opt/ruby/bin/gem arg: ["update","fastlane","-i","/Users/runner/.gem-cache"]
2020-11-05T05:19:05.8386180Z ##[debug]exec tool: /usr/local/opt/ruby/bin/gem
2020-11-05T05:19:05.8386760Z ##[debug]arguments:
2020-11-05T05:19:05.8387520Z ##[debug]   update
2020-11-05T05:19:05.8388060Z ##[debug]   fastlane
2020-11-05T05:19:05.8388900Z ##[debug]   -i
2020-11-05T05:19:05.8389670Z ##[debug]   /Users/runner/.gem-cache
2020-11-05T05:19:05.8390450Z [command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
2020-11-05T05:19:08.7333220Z Updating installed gems
2020-11-05T05:19:08.7334130Z Nothing to update
2020-11-05T05:19:08.7561030Z 
2020-11-05T05:19:08.7565030Z ##[debug]Exit code 0 received from tool '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:08.7574140Z ##[debug]STDIO streams have closed for tool '/usr/local/opt/ruby/bin/gem'
2020-11-05T05:19:08.7576530Z ##[debug]which 'fastlane'
2020-11-05T05:19:08.7579770Z ##[debug]found: '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane'
2020-11-05T05:19:08.7580980Z ##[debug]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane arg: ["deliver","submit_build","-u","it@devhaus.com","-a","com.devhaus.lj"]
2020-11-05T05:19:08.7582280Z ##[debug]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane arg: ["--skip_binary_upload","true","--skip_metadata","true","--skip_screenshots","true"]
2020-11-05T05:19:08.7583270Z ##[debug]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane arg: --force
2020-11-05T05:19:08.7584220Z ##[debug]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane arg: -p 1402634807
2020-11-05T05:19:08.7587750Z ##[debug]exec tool: /usr/local/lib/ruby/gems/2.7.0/bin/fastlane
2020-11-05T05:19:08.7588220Z ##[debug]arguments:
2020-11-05T05:19:08.7588560Z ##[debug]   deliver
2020-11-05T05:19:08.7588850Z ##[debug]   submit_build
2020-11-05T05:19:08.7589470Z ##[debug]   -u
2020-11-05T05:19:08.7590170Z ##[debug]   XXXXXXXXXXXXXXXXXXXX
2020-11-05T05:19:08.7590770Z ##[debug]   -a
2020-11-05T05:19:08.7591790Z ##[debug]   com.XXXXXXXXXXXXXXX.app
2020-11-05T05:19:08.7593020Z ##[debug]   --skip_binary_upload
2020-11-05T05:19:08.7593410Z ##[debug]   true
2020-11-05T05:19:08.7593950Z ##[debug]   --skip_metadata
2020-11-05T05:19:08.7594310Z ##[debug]   true
2020-11-05T05:19:08.7594850Z ##[debug]   --skip_screenshots
2020-11-05T05:19:08.7595210Z ##[debug]   true
2020-11-05T05:19:08.7595740Z ##[debug]   --force
2020-11-05T05:19:08.7596250Z ##[debug]   -p
2020-11-05T05:19:08.7596610Z ##[debug]   XXXXXXXXXXXXXXXXX
2020-11-05T05:19:08.7597600Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane deliver submit_build -u XXXXX@XXX.com -a com.XXX.app --skip_binary_upload true --skip_metadata true --skip_screenshots true --force -p XXXXXXXXXXXX
2020-11-05T05:19:14.2708100Z [05:19:14]: [33mSeems like launching fastlane takes a while - please run[0m
2020-11-05T05:19:14.2710090Z [05:19:14]: 
2020-11-05T05:19:14.2712260Z [05:19:14]: [36m$ [sudo] gem cleanup[0m
2020-11-05T05:19:14.2712660Z [05:19:14]: 
2020-11-05T05:19:14.2714360Z [05:19:14]: [33mto uninstall outdated gems and make fastlane launch faster[0m
2020-11-05T05:19:14.2715760Z [05:19:14]: [33mAlternatively it's recommended to start using a Gemfile to lock your dependencies[0m
2020-11-05T05:19:14.2717200Z [05:19:14]: [33mTo get started with a Gemfile, run[0m
2020-11-05T05:19:14.2717540Z [05:19:14]: 
2020-11-05T05:19:14.2718090Z [05:19:14]: [36m$ bundle init[0m
2020-11-05T05:19:14.2718790Z [05:19:14]: [36m$ echo 'gem "fastlane"' >> Gemfile[0m
2020-11-05T05:19:14.2732920Z [05:19:14]: [36m$ bundle install[0m
2020-11-05T05:19:14.2738170Z [05:19:14]: 
2020-11-05T05:19:14.2739340Z [05:19:14]: [33mAfter creating the Gemfile and Gemfile.lock, commit those files into version control[0m
2020-11-05T05:19:14.2741030Z [05:19:14]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2020-11-05T05:19:24.1688980Z [05:19:24]: Sending anonymous analytics information
2020-11-05T05:19:24.1689640Z [05:19:24]: Learn more at https://docs.fastlane.tools/#metrics
2020-11-05T05:19:24.1690020Z [05:19:24]: No personal or sensitive data is sent.
2020-11-05T05:19:24.1690380Z [05:19:24]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-11-05T05:19:24.1781480Z [05:19:24]: Login to App Store Connect (it@devhaus.com)
2020-11-05T05:19:24.6516950Z Session loaded from environment variable is not valid. Continuing with normal login.
2020-11-05T05:19:25.3933590Z Two-factor Authentication (6 digits code) is enabled for account 'it@devhaus.com'
2020-11-05T05:19:25.3934900Z More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
2020-11-05T05:19:25.3935210Z 
2020-11-05T05:19:25.3935790Z If you're running this in a non-interactive session (e.g. server or CI)
2020-11-05T05:19:25.3937020Z check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
2020-11-05T05:19:25.3937370Z 
2020-11-05T05:19:25.3941310Z /usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
2020-11-05T05:19:25.3942320Z Please enter the 6 digit code you received at +1 (â€¢â€¢â€¢) â€¢â€¢â€¢-â€¢â€¢55:
2020-11-05T05:34:02.1889040Z ##[debug]Re-evaluate condition on job cancellation for step: 'AppStorePromote'.
2020-11-05T05:34:02.2343330Z ##[error]The operation was canceled.
2020-11-05T05:34:02.2362360Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-11-05T05:34:02.2367800Z ##[section]Finishing: AppStorePromote
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by jfahrenkrug** [comment]
@trajano The log output says `Session loaded from environment variable is not valid.`. You might want to check that the string you are passing in is valid. I think it should start with `---\n- !ruby/object:HTTP::Cookie\n  name: `

**Comment by trajano** [comment]
@jfahrenkrug  per #153 they had indicated at least on the AppCenterRelease that any non-empty string would do.  Which was useful because [no one wanted to bother updating the fastlane documentation until 5 days ago](https://github.com/fastlane/fastlane/issues/17491#issuecomment-718893141) in that it does not last a day.

**Comment by SmutsMuts** [comment]
I also have an issue with this our account was updated with 2FA I need to supply the app specific password and the fastlane password in order for our release to go through, and the annoying thing here is that before we do each release I need generate a new fastlane password and then to go into the Service Connection and update these values on the App store connection otherwise it will fail. 
I would be very happy if someone had a way to solve this or if it could be fixed since Apple requires all accounts to have 2FA enabled now.

**Comment by jonsamwell** [comment]
Any update on this, I think Fastlane now uses the App Store Connect API for authentication.  This task is effectively useless as a CI task as Apple now requires 2FA on all account.

https://docs.fastlane.tools/app-store-connect-api/

**Comment by YahiaRagae** [comment]
I have done exactly the same as @jonsamwell , and got the same issue  `Unresolved conflict between options: 'api_key_path' and 'username'`

**Comment by anatolybolshakov** [comment]
Hi everyone, we released new version with api key support - please let us know if you still face with issues regarding this.
@YahiaRagae does api key feature work for you?

**Comment by akeblom** [comment]
> Hi everyone, we released new version with api key support - please let us know if you still face with issues regarding this.
> @YahiaRagae does api key feature work for you?

Still getting 

`Unresolved conflict between options: 'api_key_path' and 'username'`

**Comment by akeblom** [comment]
> Hi everyone, we released new version with api key support - please let us know if you still face with issues regarding this.
> @YahiaRagae does api key feature work for you?

There seems to be an issue over at Fastlane where username still is mandatory even if api_key_path is provided. There is a pr to fix it but it is not merged yet. That pr should solve this problem.

**Comment by anatolybolshakov** [comment]
@akeblom ok, thanks for update!

**Comment by anatolybolshakov** [comment]
Hi everyone, let me close this one at the moment since currently there is a new api key feature - please feel free to ask any further questions or report issues.
