### ISSUE TITLE
The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

### ISSUE THREAD

**Issue by AbinashPatra** [microsoft/app-store-vsts-extension#217]
## Note  
Our TFS ios builds have started failing in the Apple app store release task. The error recorded is

The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

Version is 1.183

Fast lane is also updated but no luck. The error does not seem to point to any version issues though.

Below is the log from the build logs from agent mac machine.

[2021-02-21 00:43:34Z ERR  StepsRunner] Caught exception from step: System.Exception: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug?

**Enter Task Name**: Apple App Store  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - TFS on-premises
    
    - TFS on-premises, provide the version:  16.131.28226.3
    
- Agent - Hosted or Private: 
    
    - Private. MAC OS Catalina 10.15.7
    - Fastlane - 2.175

## Issue Description
TFS ios builds have started failing in the Apple app store release task. The error recorded is

The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

Version is 1.183

Fast lane is also updated but no luck. The error does not seem to point to any version issues though.

Below is the log from the build logs from agent mac machine.

[2021-02-21 00:43:34Z ERR  StepsRunner] Caught exception from step: System.Exception: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
### Task logs

error stack trave provided above

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by SudhersonV** [comment]
The last successful build and publish was when using the version 1.178.4

2021-02-16T20:31:14.4665180Z Task         : Apple App Store Release
2021-02-16T20:31:14.4718710Z Description  : Release an app to TestFlight or the Apple App Store
2021-02-16T20:31:14.4772570Z Version      : 1.178.4
2021-02-16T20:31:14.4825810Z Author       : Microsoft Corporation
2021-02-16T20:31:14.4881620Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)


The current version, throwing this error.

2021-02-23T14:55:01.6636180Z Task         : Apple App Store Release
2021-02-23T14:55:01.6684240Z Description  : Release an app to TestFlight or the Apple App Store
2021-02-23T14:55:01.6731410Z Version      : 1.183.0
2021-02-23T14:55:01.6779310Z Author       : Microsoft Corporation

**Comment by EzzhevNikita** [comment]
@AbinashPatra Which version of agent do you use? Could you please try to upgrade it to the latest one and check if issue will be still actual for you?

**Comment by AbinashPatra** [comment]
@EzzhevNikita  We are using the agent version 2.136.1 and I believe this is the latest version. I downloaded the agent file and verified the name and it says 2.136.

**Comment by EzzhevNikita** [comment]
@AbinashPatra Could you please try to setup new [2.182.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.182.1 ) agent (you can download it by the link I've provided)? The only thing you need to add environment variable _AZP_AGENT_DOWNGRADE_DISABLED_  with _true_ value to your pipeline.

**Comment by AbinashPatra** [comment]
I did not realize that this version is available. TFS downloads  2.136 so I thought thats latest. Now I know why thought.
Coming to the issue - 2.182.1 does not connect to tfs and we assume its because TFS is http and it does not like http.
I went down to 2.174 and it's working.

**Comment by EzzhevNikita** [comment]
@AbinashPatra Since the issue was resolved for I assume we could close this ticket. Feel free to reopen it in case the issue will happen again
