### ISSUE TITLE
App Store Release task failing while downloading software component

### ISSUE THREAD

**Issue by KP1980** [microsoft/app-store-vsts-extension#229]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*:  **Bug**

**Enter Task Name**:  **App Store Release**

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      account name:  **How can I provide this in a private message**
      team project name: **How can I provide this in a private message**
      release definition name: **How can I provide this in a private message**

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **Hosted macOS**

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

App Store Release task failing with following errors:

Error 1: 

Invalid checksum on resource download for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/org.xerial.sqlite-jdbc-3.27.2.1.jar expected: 0b2eff4ff050a1e6edb0dd0435de3ef5, received: a2daec7a3056e18c1aa48cbcbf2c8bad

Error2:

A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.transporter.aspera-macos-x64-3.9.1.2020-08-10-2333-EST.jar
A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.its.epubcheck-runner-4.4.1.jar
A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.transporter.mediatoolkit-2.1.1.jar

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

[tasklog_6 (1).log](https://github.com/microsoft/app-store-vsts-extension/files/6239106/tasklog_6.1.log)
[tasklog_6.log](https://github.com/microsoft/app-store-vsts-extension/files/6239107/tasklog_6.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

Error 1:

2021-03-31T02:59:33.4087210Z ##[section]Starting: Publish to the App Store TestFlight track
2021-03-31T02:59:33.4100290Z ==============================================================================
2021-03-31T02:59:33.4100690Z Task         : Apple App Store Release
2021-03-31T02:59:33.4101040Z Description  : Release an app to TestFlight or the Apple App Store
2021-03-31T02:59:33.4101340Z Version      : 1.183.0
2021-03-31T02:59:33.4101600Z Author       : Microsoft Corporation
2021-03-31T02:59:33.4103340Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2021-03-31T02:59:33.4103850Z ==============================================================================
2021-03-31T02:59:34.0971650Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2021-03-31T03:00:00.0183350Z Successfully installed fastlane-2.179.0
2021-03-31T03:00:00.0185090Z Parsing documentation for fastlane-2.179.0
2021-03-31T03:00:00.0186140Z Installing ri documentation for fastlane-2.179.0
2021-03-31T03:00:00.0186990Z Done installing documentation for fastlane after 21 seconds
2021-03-31T03:00:00.0187590Z 1 gem installed
2021-03-31T03:00:00.0541270Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2021-03-31T03:00:02.9935160Z Updating installed gems
2021-03-31T03:00:02.9936120Z Nothing to update
2021-03-31T03:00:03.0442940Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/Android-DEV/drop/bin/iPhone/AppStore/***.iOS.ipa
2021-03-31T03:00:05.0456460Z [03:00:05]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2021-03-31T03:00:08.2351670Z [03:00:08]: Sending anonymous analytics information
2021-03-31T03:00:08.2353110Z [03:00:08]: Learn more at https://docs.fastlane.tools/#metrics
2021-03-31T03:00:08.2353800Z [03:00:08]: No personal or sensitive data is sent.
2021-03-31T03:00:08.2354300Z [03:00:08]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2021-03-31T03:00:08.2552560Z [03:00:08]: Creating authorization token for App Store Connect API
2021-03-31T03:00:13.3379690Z [03:00:13]: Ready to upload new build to TestFlight (App: **********)...
2021-03-31T03:00:13.4961110Z [03:00:13]: Going to upload updated app to App Store Connect
2021-03-31T03:00:13.4962820Z [03:00:13]: This might take a few minutes. Please don't interrupt the script.
2021-03-31T03:04:21.8458660Z [03:04:21]: [iTMSTransporter] [2021-03-31 03:04:21 UTC] <main>  INFO: Invalid checksum on resource download for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/org.xerial.sqlite-jdbc-3.27.2.1.jar expected: 0b2eff4ff050a1e6edb0dd0435de3ef5, received: a2daec7a3056e18c1aa48cbcbf2c8bad
2021-03-31T03:04:21.8460200Z 
2021-03-31T03:04:21.8461030Z [03:04:21]: [iTMSTransporter] java.lang.reflect.InvocationTargetException
2021-03-31T03:04:21.8461410Z 
2021-03-31T03:04:21.8462990Z [03:04:21]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-31T03:04:21.8464220Z 
2021-03-31T03:04:21.8465240Z [03:04:21]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-31T03:04:21.8465770Z 
2021-03-31T03:04:21.8466730Z [03:04:21]: [iTMSTransporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-31T03:04:21.8467280Z 
2021-03-31T03:04:21.8467840Z [03:04:21]: [iTMSTransporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-03-31T03:04:21.8468190Z 
2021-03-31T03:04:21.8468680Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:220)
2021-03-31T03:04:21.8469050Z 
2021-03-31T03:04:21.8469500Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:658)
2021-03-31T03:04:21.8469830Z 
2021-03-31T03:04:21.8470970Z [03:04:21]: [iTMSTransporter] Caused by: com.apple.transporter.bootstrap.BundleNotFoundException: bundle=[org.xerial.sqlite-jdbc] version=[3.27.2.1,4.0.0) not found.
2021-03-31T03:04:21.8486530Z 
2021-03-31T03:04:21.8487160Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:267)
2021-03-31T03:04:21.8487560Z 
2021-03-31T03:04:21.8488080Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)
2021-03-31T03:04:21.8488450Z 
2021-03-31T03:04:21.8489050Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)
2021-03-31T03:04:21.8489430Z 
2021-03-31T03:04:21.8489900Z [03:04:21]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
2021-03-31T03:04:21.8490300Z 
2021-03-31T03:04:21.8490600Z [03:04:21]: [iTMSTransporter] 	... 6 more
2021-03-31T03:04:21.8490820Z 
2021-03-31T03:04:21.8491130Z [03:04:21]: iTunes Transporter output above ^
2021-03-31T03:04:21.8492180Z [03:04:21]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2021-03-31T03:04:22.0744560Z 
2021-03-31T03:04:22.0745760Z [!] Error uploading ipa file: 
2021-03-31T03:04:22.0746100Z  
2021-03-31T03:04:22.1078330Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2021-03-31T03:04:22.1140370Z ##[section]Finishing: Publish to the App Store TestFlight track

Error 2:

2021-03-30T16:41:43.0231820Z ##[section]Starting: Publish to the App Store TestFlight track
2021-03-30T16:41:43.0243950Z ==============================================================================
2021-03-30T16:41:43.0244340Z Task         : Apple App Store Release
2021-03-30T16:41:43.0244700Z Description  : Release an app to TestFlight or the Apple App Store
2021-03-30T16:41:43.0245000Z Version      : 1.183.0
2021-03-30T16:41:43.0245270Z Author       : Microsoft Corporation
2021-03-30T16:41:43.0246770Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2021-03-30T16:41:43.0247260Z ==============================================================================
2021-03-30T16:41:43.4432650Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2021-03-30T16:42:09.6593710Z Successfully installed fastlane-2.179.0
2021-03-30T16:42:09.6595480Z Parsing documentation for fastlane-2.179.0
2021-03-30T16:42:09.6596770Z Installing ri documentation for fastlane-2.179.0
2021-03-30T16:42:09.6597550Z Done installing documentation for fastlane after 22 seconds
2021-03-30T16:42:09.6598090Z 1 gem installed
2021-03-30T16:42:09.6966100Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2021-03-30T16:42:13.2333280Z Updating installed gems
2021-03-30T16:42:13.2334630Z Nothing to update
2021-03-30T16:42:13.3017100Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/Android-DEV/drop/bin/iPhone/AppStore/***.iOS.ipa
2021-03-30T16:42:14.9375730Z [16:42:14]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2021-03-30T16:42:17.5508430Z [16:42:17]: Sending anonymous analytics information
2021-03-30T16:42:17.5509940Z [16:42:17]: Learn more at https://docs.fastlane.tools/#metrics
2021-03-30T16:42:17.5510480Z [16:42:17]: No personal or sensitive data is sent.
2021-03-30T16:42:17.5511040Z [16:42:17]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2021-03-30T16:42:17.5694820Z [16:42:17]: Creating authorization token for App Store Connect API
2021-03-30T16:42:20.5261610Z [16:42:20]: Ready to upload new build to TestFlight (App: *********)...
2021-03-30T16:42:20.6808400Z [16:42:20]: Going to upload updated app to App Store Connect
2021-03-30T16:42:20.6809900Z [16:42:20]: This might take a few minutes. Please don't interrupt the script.
2021-03-30T17:02:19.3076730Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3077460Z 
2021-03-30T17:02:19.3078880Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=com.apple.jingle.leghorn.fileformat.exceptions)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3079370Z 
2021-03-30T17:02:19.3080400Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3080820Z 
2021-03-30T17:02:19.3081760Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=org.apache.xmlbeans)(version>=2.5.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3082230Z 
2021-03-30T17:02:19.3083110Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3083560Z 
2021-03-30T17:02:19.3084510Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=com.apple.jingle.leghorn.software)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3085000Z 
2021-03-30T17:02:19.3085910Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3086310Z 
2021-03-30T17:02:19.3087340Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=com.apple.jingle.leghorn.fileformat)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3095300Z 
2021-03-30T17:02:19.3096350Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3096730Z 
2021-03-30T17:02:19.3097750Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=com.apple.jingle.leghorn.media)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3098170Z 
2021-03-30T17:02:19.3099250Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3099650Z 
2021-03-30T17:02:19.3100730Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(package=com.apple.jingle.leghorn.fileformat.impl)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3101180Z 
2021-03-30T17:02:19.3102090Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 	unsatisfied requirement: com.apple.transporter.aspera-win-x86
2021-03-30T17:02:19.3102570Z 
2021-03-30T17:02:19.3103550Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: 		 (&(osgi.native.osname~=Win32)(|(osgi.native.processor~=x86)(osgi.native.processor~=x86-64)))
2021-03-30T17:02:19.3104070Z 
2021-03-30T17:02:19.3105040Z [17:02:19]: [iTMSTransporter] [2021-03-30 17:02:19 UTC] <main> ERROR: could not find the service with interface (com.apple.transporter.osgi.TransporterService)
2021-03-30T17:02:19.3105530Z 
2021-03-30T17:02:19.3105870Z [17:02:19]: iTunes Transporter output above ^
2021-03-30T17:02:19.3107170Z [17:02:19]: A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.transporter.aspera-macos-x64-3.9.1.2020-08-10-2333-EST.jar
2021-03-30T17:02:19.3109150Z A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.its.epubcheck-runner-4.4.1.jar
2021-03-30T17:02:19.3110720Z A downloaded software component is corrupted and will not be used. https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.1.0/bundles/com.apple.transporter.mediatoolkit-2.1.1.jar
2021-03-30T17:02:19.3111560Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3112230Z (&(package=com.apple.transporter.mediatoolkit)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3112800Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3113300Z (&(package=com.apple.jingle.leghorn.software)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3113860Z unsatisfied requirement: com.apple.transporter.softwaresupport
2021-03-30T17:02:19.3114490Z (&(package=com.apple.jingle.leghorn.fileformat.exceptions)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3115030Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3115600Z (&(package=com.apple.jingle.leghorn.fileformat.exceptions)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3116500Z unsatisfied requirement: com.apple.transporter.aspera-macos-arm64
2021-03-30T17:02:19.3117050Z (&(|(arch~=arm64)(arch~=arm64e))(rosetta=false))
2021-03-30T17:02:19.3117550Z unsatisfied requirement: com.apple.transporter.softwaresupport
2021-03-30T17:02:19.3118050Z (&(package=com.apple.jingle.leghorn.software)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3118590Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3119080Z (&(package=com.apple.jingle.leghorn.fileformat.impl)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3119720Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3120260Z (&(package=com.apple.transporter.mediatoolkit)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3120770Z unsatisfied requirement: com.apple.transporter.softwaresupport
2021-03-30T17:02:19.3121330Z (&(package=com.apple.jingle.leghorn.fileformat)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3161860Z unsatisfied requirement: com.apple.transporter.softwaresupport
2021-03-30T17:02:19.3162520Z (&(package=com.apple.transporter.mediatoolkit)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3163660Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3164160Z (&(package=com.apple.jingle.leghorn.fileformat)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3164730Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3165280Z (&(package=com.apple.jingle.leghorn.media)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3166400Z unsatisfied requirement: com.apple.transporter.aspera-linux-x64
2021-03-30T17:02:19.3168140Z (&(osgi.native.osname~=Linux)(osgi.native.processor~=x86-64))
2021-03-30T17:02:19.3169570Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3171100Z (&(package=com.apple.jingle.leghorn.fileformat.exceptions)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3171770Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3173080Z (&(package=org.apache.xmlbeans)(version>=2.5.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3173650Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3174130Z (&(package=com.apple.jingle.leghorn.software)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3174700Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3175260Z (&(package=com.apple.jingle.leghorn.fileformat)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3175740Z unsatisfied requirement: com.apple.transporter.core
2021-03-30T17:02:19.3176570Z (&(package=com.apple.jingle.leghorn.media)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3177560Z unsatisfied requirement: com.apple.transporter.itmstransporter
2021-03-30T17:02:19.3178090Z (&(package=com.apple.jingle.leghorn.fileformat.impl)(version>=2.1.0)(!(version>=3.0.0)))
2021-03-30T17:02:19.3179100Z unsatisfied requirement: com.apple.transporter.aspera-win-x86
2021-03-30T17:02:19.3180020Z (&(osgi.native.osname~=Win32)(|(osgi.native.processor~=x86)(osgi.native.processor~=x86-64)))
2021-03-30T17:02:19.3180780Z could not find the service with interface (com.apple.transporter.osgi.TransporterService)
2021-03-30T17:02:19.3181820Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2021-03-30T17:02:19.5855240Z 
2021-03-30T17:02:19.5856130Z [!] Error uploading ipa file: 
2021-03-30T17:02:19.5856670Z  
2021-03-30T17:02:19.6102250Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2021-03-30T17:02:19.6153540Z ##[section]Finishing: Publish to the App Store TestFlight track

**Comment by DaniilShmelev** [comment]
Hi @KP1980! There is an open ticket in the fastlane repo regarding this issue: https://github.com/fastlane/fastlane/issues/18331.
As a workaround, switching to a newer version of macos worked for us.

Closing this for now since this is outside of our area. Feel free to reopen if you have any questions!

**Comment by KP1980** [comment]
Hi @DaniilShmelev 

I do not see any option to to switch to a newer version of macOS. There is only one option "Hosted MacOS" in Agent Pool selection. I have attached the screenshot.

P.S. I cannot reopen the issue if it is close by a repo collaborator.
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
![Agent Pool](https://user-images.githubusercontent.com/53361846/113307241-8ce81080-92ca-11eb-94c4-1b8fa1f19d26.PNG)

**Comment by KP1980** [comment]
Hi @DaniilShmelev

I was able to switch to newer version of macOS agent (macOS-10.15) by selecting "Azure Pipelines" and then selecting Agent Specification to "macOS-10.15".

The issue is resolved now. 

Thank you for your help.
