### ISSUE TITLE
Unable to update "release notes" in appstore  production binary using release pipeline

### ISSUE THREAD

**Issue by Aiswarya26-ui** [microsoft/app-store-vsts-extension#251]
Hi,

There's an issue in updating the release notes to appstore. The release pipeline is able to deploy the build version but fails to update the release notes to appstore production. Here's the detailed error log.

2021-05-27T12:38:19.2357650Z [12:38:19]: [33m😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date[0m
2021-05-27T12:38:31.6764920Z [12:38:31]: ✅  Passed: No broken urls
2021-05-27T12:38:31.6781240Z +-----------+----------------+
2021-05-27T12:38:31.6782040Z |     [33mPotential problems[0m     |
2021-05-27T12:38:31.6782890Z +-----------+----------------+
2021-05-27T12:38:31.6783390Z | Field     | Failure reason |
2021-05-27T12:38:31.6784180Z +-----------+----------------+
2021-05-27T12:38:31.6785000Z | copyright | [33mmissing: 2021[0m  |
2021-05-27T12:38:31.6785780Z +-----------+----------------+
2021-05-27T12:38:31.6786810Z [12:38:31]: [33m[33mprecheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍[0m
2021-05-27T12:38:31.8535930Z [12:38:31]: Selecting existing build-number: 1.1.73
2021-05-27T12:38:32.5634880Z [12:38:32]: Selecting build 1.1.73 (1.1.73)...
2021-05-27T12:38:33.4148840Z [12:38:33]: [32mSuccessfully selected build[0m
2021-05-27T12:38:37.4198240Z [12:38:37]: [32mSuccessfully updated IDFA declarations on App Store Connect[0m
2021-05-27T12:38:39.7317290Z 
2021-05-27T12:38:39.7318080Z Looking for related GitHub issues on fastlane/fastlane...
2021-05-27T12:38:39.7318300Z 
2021-05-27T12:38:39.9033420Z /Users/runner/.gem-cache/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \e[31m[!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
2021-05-27T12:38:39.9035270Z The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
2021-05-27T12:38:39.9036390Z The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request\e[0m
2021-05-27T12:38:39.9037560Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
2021-05-27T12:38:39.9038880Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:983:in `post_app_store_version_submission'
2021-05-27T12:38:39.9040090Z 	from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `post_app_store_version_submission'
2021-05-27T12:38:39.9041630Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:178:in `create_app_store_version_submission'
2021-05-27T12:38:39.9042870Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/submit_for_review.rb:26:in `submit!'
2021-05-27T12:38:39.9043890Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/runner.rb:198:in `submit_for_review'
2021-05-27T12:38:39.9045150Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/runner.rb:64:in `run'
2021-05-27T12:38:39.9046190Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/commands_generator.rb:97:in `block (2 levels) in run'
2021-05-27T12:38:39.9047280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2021-05-27T12:38:39.9048240Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2021-05-27T12:38:39.9049290Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2021-05-27T12:38:39.9051430Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2021-05-27T12:38:39.9052530Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2021-05-27T12:38:39.9053520Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
2021-05-27T12:38:39.9054960Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
2021-05-27T12:38:39.9056230Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
2021-05-27T12:38:39.9057350Z 	from /Users/runner/.gem-cache/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
2021-05-27T12:38:39.9058220Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
2021-05-27T12:38:39.9059230Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
2021-05-27T12:38:39.9497050Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2021-05-27T12:38:39.9519280Z ##[section]Finishing: Submit to the App Store for review

Thanks,
Aiswarya

P.S. The what's new was successfully uploaded to testflight track.

**Comment by anatolybolshakov** [comment]
Hi @Aiswarya26-ui this seems to be fastlane issue - have you tried to apply workarounds mentioned in https://github.com/fastlane/fastlane/issues/16700?

**Comment by anatolybolshakov** [comment]
Hi @Aiswarya26-ui do you have any updates?

**Comment by anatolybolshakov** [comment]
@Aiswarya26-ui I'm closing this at the moment since it seems to be fastlane issue.
