### ISSUE TITLE
Can not Publish to the App Store Production track

### ISSUE THREAD

**Issue by AndreyBespamyatnov** [microsoft/app-store-vsts-extension#264]
Hi I'm using the Azure DevOps task, and here is logs

My configuration of the Task

```
- task: AppStoreRelease@1
  displayName: 'Publish to the App Store Production track'
  inputs:
    serviceEndpoint: ' *****************'
    releaseTrack: Production
    appIdentifier: *****************
    ipaPath: '$(System.DefaultWorkingDirectory)/_surgentit.knowfully.studycompanion/Release_ios/studycompanion.ipa'
    skipBinaryUpload: true
    shouldSubmitForReview: true
    shouldAutoRelease: true
    fastlaneArguments: '--build_number $(buildIdWithOffset) --release_notes "{\"default\": \"We update our app regularly to provide you with the best experience and stability.\", \"en-US\": \"We update our app regularly to provide you with the best experience and stability.\", \"en-GB\": \"We update our app regularly to provide you with the best experience and stability.\"}" --submission_information "{\"uses_non_exempt_encryption\": false, \"add_id_info_uses_idfa\": false}"'

```

```
2021-12-03T14:13:07.8814680Z ##[section]Starting: Publish to the App Store Production track
2021-12-03T14:13:07.8829570Z ==============================================================================
2021-12-03T14:13:07.8830210Z Task         : Apple App Store Release
2021-12-03T14:13:07.8830630Z Description  : Release an app to TestFlight or the Apple App Store
2021-12-03T14:13:07.8830950Z Version      : 1.189.0
2021-12-03T14:13:07.8831280Z Author       : Microsoft Corporation
2021-12-03T14:13:07.8833330Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2021-12-03T14:13:07.8833910Z ==============================================================================
2021-12-03T14:13:08.9200950Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2021-12-03T14:13:42.5991380Z Successfully installed fastlane-2.198.1
2021-12-03T14:13:42.6094370Z Parsing documentation for fastlane-2.198.1
2021-12-03T14:13:42.6186160Z Installing ri documentation for fastlane-2.198.1
2021-12-03T14:13:42.6288330Z Done installing documentation for fastlane after 28 seconds
2021-12-03T14:13:42.6390150Z 1 gem installed
2021-12-03T14:13:42.7862190Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2021-12-03T14:13:46.8561980Z Updating installed gems
2021-12-03T14:13:46.8662120Z Nothing to update
2021-12-03T14:13:46.9216340Z Precheck will not check In-app purchases because Fastlane doesn't support it with the App Store Connect API Key.
2021-12-03T14:13:47.2802290Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane deliver --force --precheck_include_in_app_purchases false --api_key_path /Users/runner/work/_temp/api_key***.json -a com.surgent.studycompanion --skip_binary_upload true -j ios --skip_metadata true --skip_screenshots true --submit_for_review true --automatic_release true --build_number 11754 --release_notes {"default": "We update our app regularly to provide you with the best experience and stability.", "en-US": "We update our app regularly to provide you with the best experience and stability.", "en-GB": "We update our app regularly to provide you with the best experience and stability."} --submission_information {"uses_non_exempt_encryption": false, "add_id_info_uses_idfa": false}
2021-12-03T14:13:50.5603900Z [14:13:50]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2021-12-03T14:13:58.2109090Z [14:13:58]: Sending anonymous analytics information
2021-12-03T14:13:58.2209740Z [14:13:58]: Learn more at https://docs.fastlane.tools/#metrics
2021-12-03T14:13:58.2312060Z [14:13:58]: No personal or sensitive data is sent.
2021-12-03T14:13:58.2413710Z [14:13:58]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2021-12-03T14:13:58.2514580Z [14:13:58]: No deliver configuration found in the current directory. Do you want to setup deliver?
2021-12-03T14:13:58.2616340Z 
2021-12-03T14:13:58.2712370Z Looking for related GitHub issues on fastlane/fastlane...
2021-12-03T14:13:58.2815160Z 
2021-12-03T14:13:59.6677290Z ➡️  [regression] pilot distribute_external asks for app_platform in non-interactive mode
2021-12-03T14:13:59.6757610Z     https://github.com/fastlane/fastlane/issues/19351 [open] 10 💬
2021-12-03T14:13:59.6813900Z     22 hours ago
2021-12-03T14:13:59.6914950Z 
2021-12-03T14:13:59.6996980Z ➡️  Metadata Path is not considered
2021-12-03T14:13:59.7075080Z     https://github.com/fastlane/fastlane/issues/18321 [closed] 7 💬
2021-12-03T14:13:59.7128250Z     30 Sep 2021
2021-12-03T14:13:59.7202150Z 
2021-12-03T14:13:59.7260300Z ➡️  GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode
2021-12-03T14:13:59.7303430Z     https://github.com/fastlane/fastlane/issues/17376 [closed] 18 💬
2021-12-03T14:13:59.7344060Z     17 Feb 2021
2021-12-03T14:13:59.7396340Z 
2021-12-03T14:13:59.7445400Z and 54 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
2021-12-03T14:13:59.7498650Z 
2021-12-03T14:13:59.7537590Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2021-12-03T14:13:59.7592370Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
2021-12-03T14:13:59.7633830Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
2021-12-03T14:13:59.7702180Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
2021-12-03T14:13:59.7805640Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2021-12-03T14:13:59.7902950Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
2021-12-03T14:13:59.8005760Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2021-12-03T14:13:59.8106040Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2021-12-03T14:13:59.8208580Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2021-12-03T14:13:59.8309730Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
2021-12-03T14:13:59.8343690Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2021-12-03T14:13:59.8445010Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
2021-12-03T14:13:59.8546370Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
2021-12-03T14:13:59.8607980Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
2021-12-03T14:13:59.8693450Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
2021-12-03T14:13:59.8783280Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2021-12-03T14:13:59.8856470Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
2021-12-03T14:13:59.8926710Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
2021-12-03T14:13:59.8998040Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
2021-12-03T14:13:59.9100180Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
2021-12-03T14:13:59.9200680Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2021-12-03T14:13:59.9303990Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
2021-12-03T14:13:59.9384350Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2021-12-03T14:13:59.9487440Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2021-12-03T14:13:59.9592130Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2021-12-03T14:13:59.9690850Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
2021-12-03T14:13:59.9793720Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2021-12-03T14:13:59.9896150Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
2021-12-03T14:13:59.9996750Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
2021-12-03T14:14:00.0099860Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
2021-12-03T14:14:00.0200070Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
2021-12-03T14:14:00.0291010Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2021-12-03T14:14:00.0367480Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
2021-12-03T14:14:00.0757340Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2021-12-03T14:14:00.0991380Z ##[section]Finishing: Publish to the App Store Production track
```

**Comment by AndreyBespamyatnov** [comment]
I found a workaround: https://github.com/microsoft/app-store-vsts-extension/issues/206

**Comment by anatolybolshakov** [comment]
Hi @AndreyBespamyatnov sorry for the delay - is this issue still actual for you?

**Comment by AndreyBespamyatnov** [comment]
> Hi @AndreyBespamyatnov sorry for the delay - is this issue still actual for you?

Hi, thank you for your reply, as I provided before, I found the workaround and it works pretty well, and I still think that the issue exists.

**Comment by michaelmairegger** [comment]
@anatolybolshakov Unfortunately the issue exists.

This works

    - task: AppStoreRelease@1
      displayName: 'Deploy to "${{ parameters.iOSExternalTestersGroup }}"'
      inputs:
        serviceEndpoint: '******'
        appIdentifier: '******'
        ipaPath: '$(Pipeline.Workspace)/ios/******.ipa'
        shouldSkipWaitingForProcessing: true
        appSpecificId: '******'
        installFastlane: false
        externalTestersGroups: ${{ parameters.iOSExternalTestersGroup }}

This quits with the same error as @AndreyBespamyatnov stated

    - task: AppStoreRelease@1
      displayName: 'Promote to "${{ parameters.iOSExternalTestersGroup }}"'
      inputs:
        serviceEndpoint: '******'
        appIdentifier: '******'
        appBuildNumber: '******'
        externalTestersGroups: ${{ parameters.iOSExternalTestersGroup }}
        distributeOnly: true
        installFastlane: false

**Comment by anatolybolshakov** [comment]
@AndreyBespamyatnov @michaelmairegger as I see this is know issue which occurres when 'skipBinaryUpload' is enabled. 
To resolve it - according to the [current fastlane logic](https://github.com/fastlane/fastlane/blame/f55ec210827f1f7e6f3b77f4b19f73f1154d23f6/deliver/lib/deliver/commands_generator.rb#L69)  you can either set up 'description' property or metadata, or provide deliver file.

**Comment by SteveKennedy** [comment]
Hoping someone can point me in the right direction on this one? I still get the "No deliver configuration found in the current directory. Do you want to setup deliver?" issue.
