### ISSUE TITLE
Issue detecting xcode version in Fastlane with recent task.

### ISSUE THREAD

**Issue by devandanger** [microsoft/app-store-vsts-extension#273]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug: Can't see to kick this bug.

2022-04-14T17:35:35.0265210Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:432:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)

[app-store-vsts-extension](https://github.com/microsoft/app-store-vsts-extension)

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, progcloud, MN, build definition name/build number: Definition 33 Release 20946

- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Hosted?

## Issue Description

Continually fails, we have recently made changes to this until today while we were throwing this at the wall.

### Task logs

2022-04-14T17:35:35.0265210Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:432:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
2022-04-14T17:35:35.0267790Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/pilot/lib/pilot/build_manager.rb:394:in `new'
2022-04-14T17:35:35.0269460Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/pilot/lib/pilot/build_manager.rb:394:in `transporter_for_selected_team'
2022-04-14T17:35:35.0271480Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/pilot/lib/pilot/build_manager.rb:49:in `upload'
2022-04-14T17:35:35.0278370Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.205.1/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by AndreyIvanov42** [comment]
Hi @devandanger  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by max-zaytsev** [comment]
Hi @devandanger, is this issue still actual for you?
