### ISSUE TITLE
An exception has occurred: issuerId is required

### ISSUE THREAD

**Issue by shehanGuruge** [microsoft/app-store-vsts-extension#290]
I am using this AppStoreRelease@1 task to upload the ipa to testflight and this was working fine before. However all of a sudden I am getting this issue in azure pipelines,

```
2022-10-20T08:23:11.7589950Z ##[section]Starting: Publish to the App Store TestFlight track
2022-10-20T08:23:11.7602320Z ==============================================================================
2022-10-20T08:23:11.7602800Z Task         : Apple App Store Release
2022-10-20T08:23:11.7603190Z Description  : Release an app to TestFlight or the Apple App Store
2022-10-20T08:23:11.7603520Z Version      : 1.207.0
2022-10-20T08:23:11.7603810Z Author       : Microsoft Corporation
2022-10-20T08:23:11.7604270Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2022-10-20T08:23:11.7604810Z ==============================================================================
2022-10-20T08:23:12.0716580Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2022-10-20T08:23:47.6215200Z Successfully installed fastlane-2.210.1
2022-10-20T08:23:47.6218450Z Parsing documentation for fastlane-2.210.1
2022-10-20T08:23:47.6220190Z Installing ri documentation for fastlane-2.210.1
2022-10-20T08:23:47.6221300Z Done installing documentation for fastlane after 30 seconds
2022-10-20T08:23:47.6223090Z 1 gem installed
2022-10-20T08:23:47.6738530Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2022-10-20T08:23:51.6374450Z Updating installed gems
2022-10-20T08:23:51.6475180Z Nothing to update
2022-10-20T08:23:51.6577940Z Gems already up-to-date: fastlane
2022-10-20T08:23:51.6934660Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/1/a/dermalytics.ipa -a org.***edtech.dermalyser.dev --skip_submission true --skip_waiting_for_build_processing true -p 1643700343
2022-10-20T08:23:55.3262720Z [08:23:55]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2022-10-20T08:23:57.9735150Z [08:23:57]: Sending anonymous analytics information
2022-10-20T08:23:57.9736900Z [08:23:57]: Learn more at https://docs.fastlane.tools/#metrics
2022-10-20T08:23:57.9737830Z [08:23:57]: No personal or sensitive data is sent.
2022-10-20T08:23:57.9738510Z [08:23:57]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2022-10-20T08:23:58.0508930Z [08:23:58]: Creating authorization token for App Store Connect API
2022-10-20T08:23:58.0560910Z [08:23:58]: Ready to upload new build to TestFlight (App: xxxxxxxxxx)...
2022-10-20T08:23:58.2224270Z [08:23:58]: Going to upload updated app to App Store Connect
2022-10-20T08:23:58.2226010Z [08:23:58]: This might take a few minutes. Please don't interrupt the script.
2022-10-20T08:24:17.5961110Z [08:24:17]: Transporter transfer failed.
2022-10-20T08:24:17.5991900Z [08:24:17]: 
2022-10-20T08:24:17.6120110Z [08:24:17]: There was a general exception while executing
2022-10-20T08:24:17.6290480Z An exception has occurred: issuerId is required
2022-10-20T08:24:17.9693760Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T08:24:17.9694730Z 
2022-10-20T08:24:17.9695950Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9696900Z 
2022-10-20T08:24:17.9698440Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9698980Z 
2022-10-20T08:24:17.9700270Z [08:24:17]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T08:24:17.9701110Z 
2022-10-20T08:24:17.9702220Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:107)
2022-10-20T08:24:17.9702880Z 
2022-10-20T08:24:17.9704040Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:78)
2022-10-20T08:24:17.9705400Z 
2022-10-20T08:24:17.9706650Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
2022-10-20T08:24:17.9708150Z 
2022-10-20T08:24:17.9708810Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T08:24:17.9709190Z 
2022-10-20T08:24:17.9709790Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9710220Z 
2022-10-20T08:24:17.9710820Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9711250Z 
2022-10-20T08:24:17.9711970Z [08:24:17]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T08:24:17.9712310Z 
2022-10-20T08:24:17.9713000Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)
2022-10-20T08:24:17.9713410Z 
2022-10-20T08:24:17.9714020Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)
2022-10-20T08:24:17.9714470Z 
2022-10-20T08:24:17.9714890Z [08:24:17]: [iTMSTransporter] 
2022-10-20T08:24:17.9715080Z 
2022-10-20T08:24:17.9716510Z [08:24:17]: [iTMSTransporter] [2022-10-20 08:24:17 UTC] <main> DBG-X: Returning 1
2022-10-20T08:24:17.9716920Z 
2022-10-20T08:24:17.9717550Z [08:24:17]: iTunes Transporter output above ^
2022-10-20T08:24:17.9718150Z [08:24:17]: There was a general exception while executing
2022-10-20T08:24:17.9719000Z An exception has occurred: issuerId is required
2022-10-20T08:24:17.9719660Z Return status of iTunes Transporter was 1: There was a general exception while executing
2022-10-20T08:24:17.9720300Z \nAn exception has occurred: issuerId is required
2022-10-20T08:24:17.9721480Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2022-10-20T08:24:17.9924980Z 
2022-10-20T08:24:17.9926810Z [!] Error uploading ipa file: 
2022-10-20T08:24:17.9927310Z  
2022-10-20T08:24:18.0315070Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2022-10-20T08:24:18.0339620Z ##[section]Finishing: Publish to the App Store TestFlight track
```

Although it says the issuer id is required, issuer id has been already configured inside the service connection and also has been declared explicitly inside the task itself.

**Comment by chadcampling** [comment]
Changing to force the macos-12 hosted agent has provided a work around for us while fastlane resolve  
```diff
pool:
-  vmImage: 'macos-latest'
+  vmImage: 'macos-12'
```

https://github.com/fastlane/fastlane/issues/20741

**Comment by LiliaSabitova** [comment]
Hi @shehanGuruge you can also try setting environment variable ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD to true.
You can see the details [here](https://github.com/fastlane/fastlane/issues/20741).

**Comment by max-zaytsev** [comment]
@shehanGuruge is this problem still relevant?
