### ISSUE TITLE
Unable to submit ipa to testflight

### ISSUE THREAD

**Issue by sauprakash** [microsoft/app-store-vsts-extension#326]
## Issue Description

Unable to submit Stream iOS app to testflight.

We are using the two factor authencation and hence providing Fastlane session token  

YAML:
steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Publish to the App Store TestFlight track'
  inputs:
    serviceEndpoint: 'iammgrstream Stream service connection'
    appIdentifier: com.microsoft.stream
    ipaPath: '$(System.DefaultWorkingDirectory)/_StreamApp.iOS Release/Release/artifacts/build/Stream.ipa'
    releaseNotes: '$(System.DefaultWorkingDirectory)/_StreamApp.iOS Release/Release/Release_Notes/Whats_New.md'

### Error logs

https://dev.azure.com/onedrive/OMG/_releaseProgress?_a=release-environment-logs&releaseId=3033&environmentId=5542

**Comment by LiliaSabitova** [comment]
Hi @sauprakash, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by max-zaytsev** [comment]
Hi @sauprakash, When did that start happening?
We don't have access to your pipeline. Can you please share pipeline logs (with debug mode enabled)? Do you have logs from the previous successful run?

Have you tried using 'App Store Connect Api' instead of the Fastlane session? This is the recommended and official way of authenticating with Apple services.

**Comment by sauprakash** [comment]
This started from march 20, (I see no options to enable debug mode in pipeline). We are using the only extension which is showing on tasks list to publish "Apple App store release"

**Failed run log:**
2023-05-11T07:25:06.1836140Z ##[section]Starting: Publish to the App Store TestFlight track Specific Version
2023-05-11T07:25:06.1845220Z ==============================================================================
2023-05-11T07:25:06.1845390Z Task         : Apple App Store Release
2023-05-11T07:25:06.1845480Z Description  : Release an app to TestFlight or the Apple App Store
2023-05-11T07:25:06.1845610Z Version      : 1.218.0
2023-05-11T07:25:06.1845690Z Author       : Microsoft Corporation
2023-05-11T07:25:06.1845780Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2023-05-11T07:25:06.1845940Z ==============================================================================
2023-05-11T07:25:06.4259750Z [command]/usr/local/opt/ruby@3.0/bin/gem uninstall fastlane -a -I
2023-05-11T07:25:06.8613260Z ERROR:  While executing gem ... (Errno::ENOENT)
2023-05-11T07:25:06.8614780Z     No such file or directory @ rb_check_realpath_internal - /Users/runner/.gem-cache
2023-05-11T07:25:06.8616200Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/uninstaller.rb:51:in `realpath'
2023-05-11T07:25:06.8616710Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/uninstaller.rb:51:in `initialize'
2023-05-11T07:25:06.8617170Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:198:in `new'
2023-05-11T07:25:06.8617580Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:198:in `uninstall'
2023-05-11T07:25:06.8618360Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:184:in `uninstall_gem'
2023-05-11T07:25:06.8619410Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
2023-05-11T07:25:06.8619880Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:170:in `each'
2023-05-11T07:25:06.8620480Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
2023-05-11T07:25:06.8620940Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/commands/uninstall_command.rb:132:in `execute'
2023-05-11T07:25:06.8621340Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command.rb:327:in `invoke_with_build_args'
2023-05-11T07:25:06.8621830Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:252:in `invoke_command'
2023-05-11T07:25:06.8622250Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:192:in `process_args'
2023-05-11T07:25:06.8622820Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:150:in `run'
2023-05-11T07:25:06.8623180Z 	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/gem_runner.rb:51:in `run'
2023-05-11T07:25:06.8623500Z 	/usr/local/opt/ruby@3.0/bin/gem:10:in `<main>'
2023-05-11T07:25:06.8726930Z ##[warning]There were errors when trying to uninstall fastlane. Review the error and if required add a script to your pipeline to cleanly uninstall fastlane prior to running this task. Uninstall error: Error: The process '/usr/local/opt/ruby@3.0/bin/gem' failed with exit code 1
2023-05-11T07:25:06.8745390Z [command]/usr/local/opt/ruby@3.0/bin/gem install fastlane -v 2.211.0
2023-05-11T07:25:32.6109050Z Successfully installed fastlane-2.211.0
2023-05-11T07:25:32.6209260Z Parsing documentation for fastlane-2.211.0
2023-05-11T07:25:32.6210950Z Installing ri documentation for fastlane-2.211.0
2023-05-11T07:25:32.6211760Z Done installing documentation for fastlane after 21 seconds
2023-05-11T07:25:32.6212800Z 1 gem installed
2023-05-11T07:25:32.6529180Z ##[warning]Can't find loc string for key: ReleaseNotesRequiresApiKeyOrFS
2023-05-11T07:25:32.6532300Z ##[warning]ReleaseNotesRequiresApiKeyOrFS
2023-05-11T07:25:32.6543170Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane pilot upload -u *** -i /Users/runner/work/r1/a/_StreamApp.iOS Release/Release/artifacts/build/Stream.ipa --changelog * Use your personalized home feed to return to previously shared videos, meeting recordings and other collaboration updates.  
2023-05-11T07:25:32.6543750Z * Search for any videos in the organization using keyword or Author name. 
2023-05-11T07:25:32.6545110Z * Catch up with missed meetings using the dedicated meetings filter on home page
2023-05-11T07:25:32.6545470Z * Mark important videos as Favorites and find them anytime from the library section.  
2023-05-11T07:25:32.6545820Z * Share useful videos with your colleagues with a tap of a button. 
2023-05-11T07:25:32.6546340Z * Seamlessly access both Stream Classic & Stream (On SharePoint) video content.  -a com.microsoft.com
2023-05-11T07:25:34.5862230Z [07:25:34]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2023-05-11T07:25:37.0571690Z [07:25:37]: Sending anonymous analytics information
2023-05-11T07:25:37.0573280Z [07:25:37]: Learn more at https://docs.fastlane.tools/#metrics
2023-05-11T07:25:37.0574630Z [07:25:37]: No personal or sensitive data is sent.
2023-05-11T07:25:37.0575750Z [07:25:37]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2023-05-11T07:25:37.0967960Z [07:25:37]: Login to App Store Connect (***)
2023-05-11T07:25:37.1405980Z -------------------------------------------------------------------------------------
2023-05-11T07:25:37.1412890Z Please provide your Apple Developer Program account credentials
2023-05-11T07:25:37.1413260Z The login information you enter will be stored in your macOS Keychain
2023-05-11T07:25:37.1413800Z You can also pass the password using the `FASTLANE_PASSWORD` environment variable
2023-05-11T07:25:37.1414190Z See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
2023-05-11T07:25:37.1414800Z -------------------------------------------------------------------------------------
2023-05-11T07:25:37.1509220Z 
2023-05-11T07:25:37.1509910Z Looking for related GitHub issues on fastlane/fastlane...
2023-05-11T07:25:37.1510170Z 
2023-05-11T07:25:37.3148650Z Found no similar issues. To create a new issue, please visit:
2023-05-11T07:25:37.3150740Z https://github.com/fastlane/fastlane/issues/new
2023-05-11T07:25:37.3151530Z Run `fastlane env` to append the fastlane environment to your issue
2023-05-11T07:25:37.3152790Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': [!] Missing password for user ***, and running in non-interactive shell (RuntimeError)
2023-05-11T07:25:37.3153590Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
2023-05-11T07:25:37.3154200Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/client.rb:383:in `login'
2023-05-11T07:25:37.3154780Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/client.rb:355:in `login'
2023-05-11T07:25:37.3155490Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
2023-05-11T07:25:37.3156270Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
2023-05-11T07:25:37.3156930Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
2023-05-11T07:25:37.3157500Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/manager.rb:36:in `login'
2023-05-11T07:25:37.3158040Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/manager.rb:19:in `start'
2023-05-11T07:25:37.3158600Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-05-11T07:25:37.3159200Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-05-11T07:25:37.3159760Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-05-11T07:25:37.3160290Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-05-11T07:25:37.3161900Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-05-11T07:25:37.3162520Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-05-11T07:25:37.3163090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-05-11T07:25:37.3163710Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-05-11T07:25:37.3164280Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-05-11T07:25:37.3164870Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-05-11T07:25:37.3165430Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
2023-05-11T07:25:37.3165940Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-05-11T07:25:37.3166370Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-05-11T07:25:37.3167190Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': Missing password for user ***, and running in non-interactive shell (RuntimeError)
2023-05-11T07:25:37.3167930Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
2023-05-11T07:25:37.3168520Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/client.rb:383:in `login'
2023-05-11T07:25:37.3169090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/client.rb:355:in `login'
2023-05-11T07:25:37.3169660Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
2023-05-11T07:25:37.3170440Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
2023-05-11T07:25:37.3171090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
2023-05-11T07:25:37.3171660Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/manager.rb:36:in `login'
2023-05-11T07:25:37.3172200Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/manager.rb:19:in `start'
2023-05-11T07:25:37.3172740Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-05-11T07:25:37.3173340Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-05-11T07:25:37.3173900Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-05-11T07:25:37.3174430Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-05-11T07:25:37.3175150Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-05-11T07:25:37.3175770Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-05-11T07:25:37.3176330Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-05-11T07:25:37.3176890Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-05-11T07:25:37.3177460Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-05-11T07:25:37.3178050Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-05-11T07:25:37.3178610Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
2023-05-11T07:25:37.3179700Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-05-11T07:25:37.3180070Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-05-11T07:25:37.3331230Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2023-05-11T07:25:37.3369750Z ##[section]Finishing: Publish to the App Store TestFlight track Specific Version


**Successful run log:**
2023-02-07T06:55:04.3908690Z ##[section]Starting: Publish to the App Store TestFlight track
2023-02-07T06:55:04.3922410Z ==============================================================================
2023-02-07T06:55:04.3923130Z Task         : Apple App Store Release
2023-02-07T06:55:04.3923350Z Description  : Release an app to TestFlight or the Apple App Store
2023-02-07T06:55:04.3923630Z Version      : 1.207.0
2023-02-07T06:55:04.3923810Z Author       : Microsoft Corporation
2023-02-07T06:55:04.3924040Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2023-02-07T06:55:04.3924400Z ==============================================================================
2023-02-07T06:55:04.6914570Z [command]/usr/local/opt/ruby@3.0/bin/gem install fastlane
2023-02-07T06:55:30.4952630Z Successfully installed jwt-2.7.0
2023-02-07T06:55:30.4953480Z Successfully installed fastlane-2.211.0
2023-02-07T06:55:30.4954140Z Parsing documentation for jwt-2.7.0
2023-02-07T06:55:30.4954850Z Installing ri documentation for jwt-2.7.0
2023-02-07T06:55:30.4955700Z Parsing documentation for fastlane-2.211.0
2023-02-07T06:55:30.4956600Z Installing ri documentation for fastlane-2.211.0
2023-02-07T06:55:30.4957390Z Done installing documentation for jwt, fastlane after 21 seconds
2023-02-07T06:55:30.4957920Z 2 gems installed
2023-02-07T06:55:30.5392180Z [command]/usr/local/opt/ruby@3.0/bin/gem update fastlane -i /Users/runner/.gem-cache
2023-02-07T06:55:34.1429880Z Updating installed gems
2023-02-07T06:55:34.1433240Z Nothing to update
2023-02-07T06:55:34.1436170Z Gems already up-to-date: fastlane
2023-02-07T06:55:34.1982600Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane pilot upload -u *** -i /Users/runner/work/r1/a/_StreamApp.iOS Release/Release/artifacts/build/Stream.ipa --changelog * Use your personalized home feed to return to previously shared videos, meeting recordings and other collaboration updates.  
2023-02-07T06:55:34.1988780Z * Search for any videos in the organization using keyword or Author name. 
2023-02-07T06:55:34.2026800Z * Catch up with missed meetings using the dedicated meetings filter on home page
2023-02-07T06:55:34.2038180Z * Mark important videos as Favorites and find them anytime from the library section.  
2023-02-07T06:55:34.2039260Z * Share useful videos with your colleagues with a tap of a button. 
2023-02-07T06:55:34.2044930Z * Seamlessly access both Stream Classic & Stream (On SharePoint) video content.  -a com.microsoft.stream
2023-02-07T06:55:36.0392510Z [06:55:36]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2023-02-07T06:55:38.8416450Z [06:55:38]: Sending anonymous analytics information
2023-02-07T06:55:38.8517000Z [06:55:38]: Learn more at https://docs.fastlane.tools/#metrics
2023-02-07T06:55:38.8618680Z [06:55:38]: No personal or sensitive data is sent.
2023-02-07T06:55:38.8719690Z [06:55:38]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2023-02-07T06:55:38.8802770Z [06:55:38]: Login to App Store Connect (***)
2023-02-07T06:55:40.6098850Z [06:55:40]: Login successful
2023-02-07T06:55:43.5481660Z [06:55:43]: Ready to upload new build to TestFlight (App: 1401013624)...
2023-02-07T06:55:44.0722640Z [06:55:44]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2023-02-07T06:55:44.7244830Z [06:55:44]: Going to upload updated app to App Store Connect
2023-02-07T06:55:44.7282110Z [06:55:44]: This might take a few minutes. Please don't interrupt the script.
2023-02-07T06:56:56.8383670Z [06:56:56]: --------------------------------------------------------------------
2023-02-07T06:56:56.8384830Z [06:56:56]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
2023-02-07T06:56:56.8385870Z [06:56:56]: --------------------------------------------------------------------
2023-02-07T06:56:56.8397390Z [06:56:56]: Successfully uploaded the new binary to App Store Connect
2023-02-07T06:56:56.8399090Z [06:56:56]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
2023-02-07T06:56:56.8400470Z [06:56:56]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
2023-02-07T06:56:57.0132090Z [06:56:57]: Waiting for processing on... app_id: 1401013624, app_version: 2.2.99, build_version: 343220230207064019, platform: IOS
2023-02-07T06:56:57.3771050Z [06:56:57]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
2023-02-07T06:56:57.3772380Z [06:56:57]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2023-02-07T06:57:27.5245570Z [06:57:27]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2023-02-07T06:57:58.2791650Z [06:57:58]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2023-02-07T06:58:28.5715100Z [06:58:28]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2023-02-07T06:59:01.8891160Z [06:59:01]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T06:59:32.3419410Z [06:59:32]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:00:03.1696790Z [07:00:03]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:00:33.6928590Z [07:00:33]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:01:04.0913650Z [07:01:04]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:01:34.6037720Z [07:01:34]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:02:04.9594790Z [07:02:04]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:02:35.3276510Z [07:02:35]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:03:05.8322420Z [07:03:05]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:03:36.2986180Z [07:03:36]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:04:06.9114910Z [07:04:06]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:04:37.5260710Z [07:04:37]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:05:07.9101110Z [07:05:07]: Waiting for App Store Connect to finish processing the new build (2.2.99 - 343220230207064019) for IOS
2023-02-07T07:05:41.9949610Z [07:05:41]: Successfully finished processing the build 2.2.99 - 343220230207064019 for IOS
2023-02-07T07:05:42.4621390Z [07:05:42]: Successfully set the changelog for build
2023-02-07T07:05:42.4622760Z [07:05:42]: Using App Store Connect's default for notifying external testers (which is true) - set `notify_external_testers` for full control
2023-02-07T07:05:42.4623820Z [07:05:42]: Distributing new build to testers: 2.2.99 - 343220230207064019
2023-02-07T07:05:42.4624750Z [07:05:42]: Successfully distributed build to Internal testers 🚀
2023-02-07T07:05:42.4891430Z ##[section]Finishing: Publish to the App Store TestFlight track

**Comment by max-zaytsev** [comment]
> [warning]There were errors when trying to uninstall fastlane. Review the error and if required add a script to your pipeline to cleanly uninstall fastlane prior to running this task. 

Have you tried adding a bash step before "Apple App Store Release" with the command below and installing the latest version of Fastlane (2.213.0)?
`gem uninstall fastlane -a -I `

**Comment by max-zaytsev** [comment]
> ask_for_login': [!] Missing password for user ***, and running in non-interactive shell (RuntimeError)

The issue was resolved. The Password was missing in a service connection.
