### ISSUE TITLE
undefined method `team_id' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by AlCapown** [microsoft/app-store-vsts-extension#328]
I am receiving the following error when trying to upload to the production track

```
`find_app': undefined method `team_id' for nil:NilClass (NoMethodError)
```

I have tried specifying the team_id in both the dedicated field and as well as an additional Fastlane argument and I still see the same issue. 

Command:

```
2023-05-18T19:58:43.1288910Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane deliver --force --precheck_include_in_app_purchases false --api_key_path /Users/runner/work/_temp/api_key***.json -a com.x.x -i /Users/runner/work/r1/a/_x-ios-prod-build/ios/x.ipa -j ios --skip_metadata true --skip_screenshots true --submit_for_review true --automatic_release false
```

StackTrace:

```
2023-05-18T19:58:49.3153140Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/detect_values.rb:54:in `find_app': [!] undefined method `team_id' for nil:NilClass (NoMethodError)
2023-05-18T19:58:49.3154700Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/detect_values.rb:17:in `run!'
2023-05-18T19:58:49.3155150Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:25:in `initialize'
2023-05-18T19:58:49.3155570Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:82:in `new'
2023-05-18T19:58:49.3156070Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
2023-05-18T19:58:49.3156520Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-05-18T19:58:49.3156900Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-05-18T19:58:49.3157370Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-05-18T19:58:49.3157800Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-05-18T19:58:49.3158290Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-05-18T19:58:49.3158770Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:187:in `run'
2023-05-18T19:58:49.3159610Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:18:in `start'
2023-05-18T19:58:49.3160160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-05-18T19:58:49.3160610Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
2023-05-18T19:58:49.3160840Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-05-18T19:58:49.3162340Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
```

**Comment by ivanduplenskikh** [comment]
Hi @AlCapown thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by andriikut** [comment]
Any updates on this?

**Comment by abdu292** [comment]
@ivanduplenskikh Experiencing this issue on Azure DevOps.
It'd be really great if you could let's if it's planned, or not planned etc, that'd help us to plan or postpone this task to a future date until this is fixed.
Only needed an update. Thanks a bunch!

**Comment by ayushmng** [comment]
Same here, any progress ?
