### ISSUE TITLE
app-store-release.js ##[error]File not found

### ISSUE THREAD

**Issue by ahmedsopeah** [microsoft/app-store-vsts-extension#386]
I am using the extension of the Apple App Store release task with the version 1.234.0

But I am facing the below error 

the task config 

`steps:
- task: AppStoreRelease@1
  displayName: 'Publish to the App Store TestFlight track'
  inputs:
    serviceEndpoint: 'apple_store_connect'`

logs 

`##[debug]Evaluating condition for step: 'Publish to the App Store TestFlight track'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Publish to the App Store TestFlight track
==============================================================================
Task         : Apple App Store Release
Description  : Release an app to TestFlight or the Apple App Store
Version      : 1.234.0
Author       : Microsoft Corporation
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
==============================================================================
##[debug]Resource Utilization warnings is disabled, switch "DISABLE_RESOURCE_UTILIZATION_WARNINGS" variable to "false" if you want to enable it
##[error]File not found: '/Users/ahmadsobeeh/myagent/_work/_tasks/AppStoreRelease_2e371150-da5e-11e5-83da-0943b1acc572/1.234.0/app-store-release.js'
##[debug]System.IO.FileNotFoundException: File not found: '/Users/ahmadsobeeh/myagent/_work/_tasks/AppStoreRelease_2e371150-da5e-11e5-83da-0943b1acc572/1.234.0/app-store-release.js'
File name: '/Users/ahmadsobeeh/myagent/_work/_tasks/AppStoreRelease_2e371150-da5e-11e5-83da-0943b1acc572/1.234.0/app-store-release.js'
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtilInstanced.File(String fileName, String name) in /Users/runner/work/1/s/src/Agent.Sdk/Util/ArgUtil/ArgUtilInstanced.cs:line 45
   at Microsoft.VisualStudio.Services.Agent.Util.ArgUtil.File(String fileName, String name) in /Users/runner/work/1/s/src/Agent.Sdk/Util/ArgUtil/ArgUtil.cs:line 27
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync() in /Users/runner/work/1/s/src/Agent.Worker/Handlers/NodeHandler.cs:line 133
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsyncInternal() in /Users/runner/work/1/s/src/Agent.Worker/TaskRunner.cs:line 446
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /Users/runner/work/1/s/src/Agent.Worker/TaskRunner.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /Users/runner/work/1/s/src/Agent.Worker/StepsRunner.cs:line 264
##[section]Finishing: Publish to the App Store TestFlight track
`

TS 
I removed the extension and reinstalled it 
I installed the version of 1.245.0 manually with tfx cli 
but since if I removed the extension from the UI does not effect in the pipeline and still task working. i tried to remove it with tfc cli 
it removed 
installed it back from the UI but does not reflected and the pipeline did not recognize the task
I installed it from the tfx and it showed again in the pipeline but with same error 

I tried both versions of 1.245.0  and   1.234.0 so

**Comment by ahmedsopeah** [comment]
I used the command of tfx build tasks upload --task-path ./Tasks/AppStoreRelease/ to upload the task
