### ISSUE TITLE
fastlane complains about "uninitialized constant Colored2::EXTRAS"

### ISSUE THREAD

**Issue by yacaovsnc** [Microsoft/app-store-vsts-extension#57]
The extension failed to publish to AppStore with below error: 
```
2017-02-03T11:43:20.3536500Z [command]fastlane pilot upload -u ******** -i /Users/xplatalm/agent.coreclr.109/_work/10/a/build.sym/Release-iphoneos/xcode7ObjectiveC.ipa --skip_submission true --skip_waiting_for_build_processing true
2017-02-03T11:43:21.3753770Z /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/disable_colors.rb:12:in `<class:String>': uninitialized constant Colored2::EXTRAS (NameError)
2017-02-03T11:43:21.3771540Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/disable_colors.rb:6:in `<top (required)>'
2017-02-03T11:43:21.3787840Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3803890Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3820750Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/ui.rb:26:in `<top (required)>'
2017-02-03T11:43:21.3837760Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3855150Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3871620Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core.rb:27:in `<top (required)>'
2017-02-03T11:43:21.3888890Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3905680Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3921050Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
2017-02-03T11:43:21.3936370Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3952190Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-02-03T11:43:21.3967650Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/fastlane/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
2017-02-03T11:43:21.3982820Z 	from /Users/xplatalm/.gem-cache/gems/fastlane-2.14.1/bin/fastlane:15:in `<top (required)>'
2017-02-03T11:43:21.3997700Z 	from /Users/xplatalm/.gem-cache/bin/fastlane:23:in `load'
2017-02-03T11:43:21.4012030Z 	from /Users/xplatalm/.gem-cache/bin/fastlane:23:in `<main>'
2017-02-03T11:43:21.4024720Z ##[debug]rc:1
2017-02-03T11:43:21.4056090Z ##[debug]success:false
2017-02-03T11:43:21.4066620Z ##[debug]task result: Failed
2017-02-03T11:43:21.4090080Z ##[error]Error: fastlane failed with return code: 1
```

**Comment by yacaovsnc** [comment]
This is [reported](https://github.com/fastlane/fastlane/issues/8100) and [fixed](https://github.com/fastlane/fastlane/pull/8103) in fastlane repo.

@KrauseFx FYI.  It appears our customers will be impacted till that fix is released.

**Comment by KrauseFx** [comment]
Sorry about that, we're working on a fix 👍

**Comment by KrauseFx** [comment]
Does the new release fix it?

**Comment by yacaovsnc** [comment]
Yes @KrauseFx the new release fixed it.  Thank you very much for quick turnarounds!

**Comment by KrauseFx** [comment]
Great to hear 🚀 Sorry for breaking things briefly
