### ISSUE TITLE
Extension fails to upload the binary: uninitialized constant Bundler::Plugin::API::Source

### ISSUE THREAD

**Issue by Jossif** [Microsoft/app-store-vsts-extension#60]
``` 
2017-03-01T10:16:33.5277550Z /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
 
2017-03-01T10:16:33.5296750Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
 
2017-03-01T10:16:33.5315480Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
 
2017-03-01T10:16:33.5334100Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
 
2017-03-01T10:16:33.5352480Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
 
2017-03-01T10:16:33.5370880Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
 
2017-03-01T10:16:33.5389290Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
 
2017-03-01T10:16:33.5407680Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
 
2017-03-01T10:16:33.5426050Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
 
2017-03-01T10:16:33.5444130Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
 
2017-03-01T10:16:33.5462500Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
 
2017-03-01T10:16:33.5481660Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
 
2017-03-01T10:16:33.5500590Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
 
2017-03-01T10:16:33.5520720Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
 
2017-03-01T10:16:33.5539300Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
 
2017-03-01T10:16:33.5557530Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
 
2017-03-01T10:16:33.5575910Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
 
2017-03-01T10:16:33.5594320Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.5/lib/bundler.rb:12:in `<top (required)>'
 
2017-03-01T10:16:33.5612460Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
 
2017-03-01T10:16:33.5630020Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
 
2017-03-01T10:16:33.5647260Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
 
2017-03-01T10:16:33.5664430Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
 
2017-03-01T10:16:33.5681560Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
 
2017-03-01T10:16:33.5699110Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5716450Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5733580Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
 
2017-03-01T10:16:33.5750690Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5767910Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5784900Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane.rb:22:in `<top (required)>'
 
2017-03-01T10:16:33.5803320Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5821590Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
 
2017-03-01T10:16:33.5839570Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
 
2017-03-01T10:16:33.5856370Z 	from /Users/builder/.gem-cache/gems/fastlane-2.18.3/bin/fastlane:15:in `<top (required)>'
 
2017-03-01T10:16:33.5873030Z 	from /Users/builder/.gem-cache/bin/fastlane:23:in `load'
 
2017-03-01T10:16:33.5889360Z 	from /Users/builder/.gem-cache/bin/fastlane:23:in `<main>'
 
2017-03-01T10:16:33.5903860Z ##[debug]rc:1
 
2017-03-01T10:16:33.5916340Z ##[debug]success:false
 
2017-03-01T10:16:33.5928830Z ##[debug]task result: Failed
 
2017-03-01T10:16:33.6013110Z ##[error]Error: fastlane failed with return code: 1
 
2017-03-01T10:16:33.6026010Z ##[debug]Processed: ##vso[task.issue type=error;]Error: fastlane failed with return code: 1
 
2017-03-01T10:16:33.6047820Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: fastlane failed with return code: 1
```

I've tried with different bundler versions:
bundler-1.14.5, bundler-1.14.3

**Comment by jeffyoung** [comment]
Hi @Jossif.  It appears this was an issue with bundler (https://github.com/bundler/bundler/issues/5488) that has apparently been fixed (although I don't see a release with the fix).  That thread indicates that version 1.13.4 should still work.

As an aside, which task was causing the error?  I don't believe the tasks install bundler so I'm trying to understand what your build process is.  Are you managing the bundler installation and then trying to run a build with this extension installed?

**Comment by josephayoung** [comment]
I can report the same issue with my App Store Build task, using only the task defaults. It's grabbing the bad bundler version during the fastlane gem install, so this will probably affect everybody until the aforementioned fix is released. I couldn't find a way to override the bundler/fastlane version -- is there one? 

```
2017-03-02T22:13:07.7524690Z ##[section]Starting: Publish to the App Store TestFlight track
2017-03-02T22:13:08.0512830Z d16d4221-d33b-4eff-ae89-809a91fe4f37 exists true
2017-03-02T22:13:08.0619620Z [command]/usr/bin/gem install fastlane
2017-03-02T22:13:46.5361960Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for frameit/lib/assets/empty.png, skipping
2017-03-02T22:13:55.8501590Z Successfully installed fastlane-2.19.1
2017-03-02T22:13:55.8516460Z Parsing documentation for fastlane-2.19.1
2017-03-02T22:13:55.8529230Z 1 gem installed
2017-03-02T22:13:55.9247000Z [command]/usr/bin/gem update fastlane -i /Users/vso112771/.gem-cache
2017-03-02T22:13:58.8054300Z Updating installed gems
2017-03-02T22:13:58.8060890Z Nothing to update
2017-03-02T22:13:58.8699580Z [command]fastlane pilot upload -u ******** -i /Users/vso112771/vsts-agent/_work/3/s/bin/ios/release/Conseris.ipa --skip_waiting_for_build_processing true
2017-03-02T22:13:59.9453820Z /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
2017-03-02T22:13:59.9470990Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
2017-03-02T22:13:59.9489790Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
2017-03-02T22:13:59.9505180Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
2017-03-02T22:13:59.9519740Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-02T22:13:59.9536050Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-02T22:13:59.9548330Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
2017-03-02T22:13:59.9557400Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
2017-03-02T22:13:59.9566280Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
2017-03-02T22:13:59.9575000Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
2017-03-02T22:13:59.9583900Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
2017-03-02T22:13:59.9592950Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
2017-03-02T22:13:59.9602500Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
2017-03-02T22:13:59.9611290Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-02T22:13:59.9620070Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-02T22:13:59.9634070Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
2017-03-02T22:13:59.9643310Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
2017-03-02T22:13:59.9652060Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler.rb:12:in `<top (required)>'
2017-03-02T22:13:59.9660760Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
2017-03-02T22:13:59.9669670Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
2017-03-02T22:13:59.9678490Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
2017-03-02T22:13:59.9687820Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
2017-03-02T22:13:59.9699990Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
2017-03-02T22:13:59.9708990Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9717930Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9726780Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
2017-03-02T22:13:59.9796140Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9805190Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9813830Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane.rb:22:in `<top (required)>'
2017-03-02T22:13:59.9823180Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9832070Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-02T22:13:59.9841490Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
2017-03-02T22:13:59.9850560Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
2017-03-02T22:13:59.9858740Z 	from /usr/local/bin/fastlane:23:in `load'
2017-03-02T22:13:59.9866710Z 	from /usr/local/bin/fastlane:23:in `<main>'
2017-03-02T22:14:00.0181780Z ##[error]Error: fastlane failed with return code: 1
2017-03-02T22:14:00.1086000Z ##[section]Finishing: Publish to the App Store TestFlight track
```

**Comment by jeffyoung** [comment]
Unfortunately, at this time, there isn't a way to override the fastlane version.  However, I'm currently working on a PR that will allow it.  Furthermore, it will allow you to decide whether you even want the fastlane tools installed at all.

**Comment by jeffyoung** [comment]
I just merged the PR that allows making fastlane installation optional (as well as allowing you to choose a particular version).  The README has also been updated.  The marketplace has the new version so it should now be available to you.

Please try it out and let us know if you see any issues.  Thanks!

**Comment by josephayoung** [comment]
The manual version selection works like a charm! 

Unfortunately, I couldn't get it to solve this particular issue, as the bad bundler version (1.14.4) is still being used no matter which fastlane version is selected. I even tried going all the way back to fastlane 1.92.0, which was the most recent version that doesn't reference bundler (at least as a runtime dependency), and it still invoked bundler 1.14.4 (and this is even though 1.14.6 is the latest released version). 

This is using a VSTS hosted build agent -- is there a cached toolkit on those maybe? I was trying to figure out how to run "gem install bundler" prior to the fastlane task to see if it might update to 1.14.6, but no luck so far. 

```
2017-03-04T01:31:20.7460760Z ##[section]Starting: Publish to the App Store TestFlight track
2017-03-04T01:31:21.0514520Z d16d4221-d33b-4eff-ae89-809a91fe4f37 exists true
2017-03-04T01:31:21.0639840Z [command]/usr/bin/gem install fastlane -v 1.92.0
2017-03-04T01:32:56.0346460Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/GridExampleScreenshot.png, skipping
2017-03-04T01:32:56.0361960Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/ipadair.png, skipping
2017-03-04T01:32:56.0377420Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/iphone4s.png, skipping
2017-03-04T01:32:56.0392760Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/iphone5s.png, skipping
2017-03-04T01:32:56.0408160Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/iphone6s.png, skipping
2017-03-04T01:32:56.0423580Z unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/fastlane/actions/device_grid/assets/iphone6splus.png, skipping
2017-03-04T01:33:03.1883120Z Successfully installed spaceship-0.39.0
2017-03-04T01:33:03.1896690Z Successfully installed xcode-install-1.4.0
2017-03-04T01:33:03.1910230Z Successfully installed fastlane-1.92.0
2017-03-04T01:33:03.1923350Z Parsing documentation for spaceship-0.39.0
2017-03-04T01:33:03.1936190Z Installing ri documentation for spaceship-0.39.0
2017-03-04T01:33:03.1948960Z Parsing documentation for xcode-install-1.4.0
2017-03-04T01:33:03.1961810Z Installing ri documentation for xcode-install-1.4.0
2017-03-04T01:33:03.1974570Z Parsing documentation for fastlane-1.92.0
2017-03-04T01:33:03.1990460Z Installing ri documentation for fastlane-1.92.0
2017-03-04T01:33:03.2003940Z 3 gems installed
2017-03-04T01:33:03.2726320Z [command]fastlane pilot upload -u ******** -i /Users/vso112771/vsts-agent/_work/3/s/bin/ios/release/Conseris.ipa --skip_waiting_for_build_processing true
2017-03-04T01:33:04.4365540Z /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
2017-03-04T01:33:04.4375240Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
2017-03-04T01:33:04.4384440Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
2017-03-04T01:33:04.4393500Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
2017-03-04T01:33:04.4402500Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-04T01:33:04.4411840Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-04T01:33:04.4420840Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
2017-03-04T01:33:04.4433100Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
2017-03-04T01:33:04.4447670Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
2017-03-04T01:33:04.4460090Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
2017-03-04T01:33:04.4469080Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
2017-03-04T01:33:04.4478050Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
2017-03-04T01:33:04.4486950Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
2017-03-04T01:33:04.4496140Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-04T01:33:04.4504870Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
2017-03-04T01:33:04.4513630Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
2017-03-04T01:33:04.4528120Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
2017-03-04T01:33:04.4542670Z 	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler.rb:12:in `<top (required)>'
2017-03-04T01:33:04.4557160Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
2017-03-04T01:33:04.4571910Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
2017-03-04T01:33:04.4586720Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
2017-03-04T01:33:04.4601450Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
2017-03-04T01:33:04.4615750Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
2017-03-04T01:33:04.4629990Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4645330Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4660650Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
2017-03-04T01:33:04.4675390Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4689990Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4704730Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane.rb:22:in `<top (required)>'
2017-03-04T01:33:04.4719290Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4734250Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
2017-03-04T01:33:04.4749050Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
2017-03-04T01:33:04.4763610Z 	from /Users/vso112771/.gem-cache/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
2017-03-04T01:33:04.4777480Z 	from /usr/local/bin/fastlane:23:in `load'
2017-03-04T01:33:04.4791060Z 	from /usr/local/bin/fastlane:23:in `<main>'
2017-03-04T01:33:04.4953410Z ##[error]Error: fastlane failed with return code: 1
2017-03-04T01:33:04.5267700Z ##[section]Finishing: Publish to the App Store TestFlight track
```

**Comment by jeffyoung** [comment]
OK.  I see what's happening there.  Even though the version of fastlane you requested to be installed is being installed (at least, _reported_ to be installed), it is still using 2.19.1 (see the fifth log line up from the bottom).  So that's why it's still calling bundler.

It appears that you'll need to uninstall that version of fastlane (2.19.1) before we can go back to a previous version.  There's some detail about how to do this [here](http://stackoverflow.com/questions/5902488/uninstall-old-versions-of-ruby-gems).  I'll have a look to see if it makes sense to add this capability to the task (and, if so, how).

Thanks for trying it out and reporting back!

**Comment by jeffyoung** [comment]
Hi @josephayoung and @Jossif.

I see that a new version of bundler with the fix has been released.  However, as I see it, it appears that even if we install a later version of fastlane, as long as the bundler dependency is fulfilled (a version of bundler that's in the range that fastlane requires is present locally), bundler won't be updated.  For instance, I had bundler 1.13.7 and installed the latest version of fastlane.  fastlane was just fine with that version of bundler (even though it might have had this particular error).  Only until I had uninstalled bundler did it get updated when I installed a later version of fastlane.

Although I can add functionality to the task to uninstall a version (or all versions) of fastlane, unless the bug is in fastlane itself, it wouldn't protect this particular issue type.  In that case, you'd still need access to the build machine to remove the bad bundler, and _then_ reinstall fastlane.  And if you're on the build machine to remove the bad bundler, you may as well install the version of fastlane you want as well.
