### ISSUE TITLE
FastLane Failed checking for Github issues but carried on uploading

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/app-store-vsts-extension#84]
Uploading app to Testflight failed with the following error:

> Looking for related GitHub issues on fastlane/fastlane...
> 2017-11-22T10:39:22.4302110Z 
> 2017-11-22T10:39:23.1372660Z ➡️  Operation not supported on socket @ rb_ioctl
> 2017-11-22T10:39:23.1383700Z     https://github.com/fastlane/fastlane/issues/10983 [open] 3 💬
> 2017-11-22T10:39:23.1393670Z     6 hours ago
> 2017-11-22T10:39:23.1397690Z 
> 2017-11-22T10:39:23.1406890Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
> 2017-11-22T10:39:23.1418350Z /Users/chrisjohn/.gem-cache/gems/tty-screen-0.6.2/lib/tty/screen.rb:170:in `ioctl': [!] Operation not supported on socket @ rb_ioctl - <STDERR> (Errno::EOPNOTSUPP)
> 2017-11-22T10:39:23.1429310Z 	from /Users/chrisjohn/.gem-cache/gems/tty-screen-0.6.2/lib/tty/screen.rb:170:in `ioctl?'
> 2017-11-22T10:39:23.1440060Z 	from /Users/chrisjohn/.gem-cache/gems/tty-screen-0.6.2/lib/tty/screen.rb:162:in `size_from_ioctl'
> 2017-11-22T10:39:23.1450660Z 	from /Users/chrisjohn/.gem-cache/gems/tty-screen-0.6.2/lib/tty/screen.rb:42:in `size'
> 2017-11-22T10:39:23.1461170Z 	from /Users/chrisjohn/.gem-cache/gems/tty-screen-0.6.2/lib/tty/screen.rb:54:in `width'
> 2017-11-22T10:39:23.1471960Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:80:in `header'
> 2017-11-22T10:39:23.1482860Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
> 2017-11-22T10:39:23.1493950Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/itunes_transporter.rb:374:in `upload'
> 2017-11-22T10:39:23.1504910Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/pilot/lib/pilot/build_manager.rb:23:in `upload'
> 2017-11-22T10:39:23.1515680Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:60:in `block (2 levels) in run'
> 2017-11-22T10:39:23.1526530Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
> 2017-11-22T10:39:23.1537170Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
> 2017-11-22T10:39:23.1547900Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
> 2017-11-22T10:39:23.1559040Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
> 2017-11-22T10:39:23.1569870Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
> 2017-11-22T10:39:23.1580980Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:160:in `run'
> 2017-11-22T10:39:23.1591370Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/pilot/lib/pilot/commands_generator.rb:12:in `start'
> 2017-11-22T10:39:23.1601660Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
> 2017-11-22T10:39:23.1612610Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
> 2017-11-22T10:39:23.1622440Z 	from /Users/chrisjohn/.gem-cache/bin/fastlane:23:in `load'
> 2017-11-22T10:39:23.1632070Z 	from /Users/chrisjohn/.gem-cache/bin/fastlane:23:in `<main>'
> 2017-11-22T10:39:23.1642410Z 	from /Users/chrisjohn/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
> 2017-11-22T10:39:23.1652340Z 	from /Users/chrisjohn/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
> 2017-11-22T10:39:23.8914340Z ##[error]Error: fastlane failed with return code: 1
> 2017-11-22T10:39:23.9297750Z ##[section]Finishing: Publish to the App Store TestFlight track

But this upload actually continued and uploaded my package to testflight.

The two questions are:

- Why did the above error the upload
- why did the above continue to upload on failure

-

**Comment by piotrmurach** [comment]
Released `v0.6.3` that should fix this issue. Do you mind installing latest `tty-screen` and rerunning your app script?

**Comment by JKennedy24** [comment]
I'm not sure if I can install the latest `tty-screen` or whether that needs to be done as part of this github project.

I also think that only fixes the github issues referenced in this issue: https://github.com/fastlane/fastlane/issues/10983

not the fact that this upload script failed on finding a github issue but continued to upload.

**Comment by couper321** [comment]
My 1.* Apple Store Release task with the latest fastlane is producing this error.

**Comment by JKennedy24** [comment]
Still getting this - I would imagine this affects everyone using this plugin.

Essentially rendering this plugin useless

**Comment by piotrmurach** [comment]
Unfortunately I don't use this plugin and I don't use Windows. However, the backtrace that you have shown contains an error generated by my Ruby library `tty-screen`. I have since fixed the issue which has been confirmed by many users of `fastlane` to be working fine.  

My advice would be to manually install the `v0.6.3` version of the gem which is the latest one by going to your power shell and running the following command for your Ruby installation:

```
gem install tty-screen
```

Once the command succeeds please run your extension again.

**Comment by couper321** [comment]
Not sure on @JKennedy24 's setup but for me I'm just using Microsoft's Visual Studio Team Services Apple Release build task that's obviously using the outdated FastLane version which is failing and causing my other build tasks afterwards to fail.  Essentially Microsoft just need to update their VSTS plugin to incorporate the latest FastLane update you pushed up. 👍

**Comment by madhurig** [comment]
@couper321 @JKennedy24: The tasks in the VSTS extension does not package fastlane, it uses the version installed on the build server and provides an option to update it via the tasks. This option is available under the "Advanced" section:
<img width="241" alt="screen shot 2017-12-06 at 6 16 23 pm" src="https://user-images.githubusercontent.com/3269636/33690470-a2fcdede-dab1-11e7-9b1b-d3bf7f8d0f9f.png">

If you use the [Cloud hosted macOS VMs in VSTS](https://blogs.msdn.microsoft.com/devops/2017/11/16/cloud-hosted-mac-agents-for-ci-cd-pipelines/), these are the versions of the gems that are pre-installed on the VMs:
commander-fastlane (4.4.5)
fastlane (2.68.0)
tty-screen (0.6.3)

@piotrmurach: Thanks for your responses and suggestions. The VSTS extension that allows publishing to the Apple App Store has to be run on macOS. 

Thanks,
Madhuri

**Comment by couper321** [comment]
Nice to know, thanks for the clarification @madhurig 👍

**Comment by JKennedy24** [comment]
@madhurig Thanks for the clarification.
I have updated my tty-screen and will test with my next release cycle.

I will report back if this fixes the error.

Thanks for the help
